In [1]:
import pandas as pd

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", None)

In [2]:
from google.colab import drive

drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
wefarm = pd.read_parquet("/content/drive/MyDrive/DataKit_WeFarm/wefarm.parquet")

In [4]:
wefarm["response_sent_dt"] = pd.to_datetime(wefarm["response_sent"], format="ISO8601")
wefarm["question_set_dt"] = pd.to_datetime(wefarm["question_sent"], format="ISO8601")

In [5]:

def parse_datetime_col(df, colstr):
  df[f'{colstr}_year'] = df[colstr].dt.year
  df[f'{colstr}_month'] = df[colstr].dt.month
  df[f'{colstr}_day'] = df[colstr].dt.day
  df[f'{colstr}_hour'] = df[colstr].dt.hour
  df[f'{colstr}_minute'] = df[colstr].dt.minute
  df[f'{colstr}_second'] = df[colstr].dt.second
  df[f'{colstr}_day_name'] = df[colstr].dt.day_name()
  df[f'{colstr}_day_of_week'] = df[colstr].dt.day_of_week
  df[f'{colstr}_month_name'] = df[colstr].dt.month_name()
  df[f'{colstr}_quarter'] = df[colstr].dt.quarter
  df[f'{colstr}_week'] = df[colstr].dt.isocalendar().week
  df[f'{colstr}_date'] = df[colstr].dt.date
  df[f'{colstr}_time'] = df[colstr].dt.time

  return df

In [6]:
wefarm = parse_datetime_col(wefarm, "response_sent_dt")
wefarm = parse_datetime_col(wefarm, "question_set_dt")

In [7]:
niche = pd.read_parquet("/content/drive/MyDrive/DataKit_WeFarm/en_questions_cat_niche.parquet")
broad = pd.read_parquet("/content/drive/MyDrive/DataKit_WeFarm/en_questions_cat_broad.parquet")

In [8]:
all = pd.merge(wefarm, niche, on="question_id").merge(
  broad, on="question_id"
)

In [9]:
import json

with open("/content/drive/MyDrive/DataKit_WeFarm/segment_user_ids.json", "r") as r:
    segment_user_id_dct = json.load(r)

In [10]:
segment_user_id_dct.keys()

dict_keys(['user_activity_post_count', 'speed_post_response', 'unique_askers', 'tenure'])

In [11]:
# segment_user_id_dct["user_activity_post_count"].keys()

In [12]:
from collections import defaultdict

user_segments = defaultdict(dict)
for agg, dct in segment_user_id_dct.items():
  for segment, user_ids in dct.items():
    for user_id in user_ids:
      user_segments[user_id][agg] = segment

row_lst = []
for user_id, segments in user_segments.items():
  row = {"user_id": user_id}
  row.update(segments)
  row_lst.append(row)

user_segments_df = pd.DataFrame(row_lst)

In [13]:
all1 = all.merge(user_segments_df, left_on="question_user_id", right_on="user_id", how="inner")

In [14]:
all2 = all1[all1["question_user_country_code"].isin(["ug", "ke"])]

In [15]:
all3 = all2.drop_duplicates("question_id")

In [16]:
all3["question_user_country_code"] = [j.upper() for j in all3["question_user_country_code"]]

/tmp/ipython-input-4026003717.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  all3["question_user_country_code"] = [j.upper() for j in all3["question_user_country_code"]]

# define topics lists

In [17]:
all3.iloc[:5, 54:173]

,financial-inclusion_price,financial-inclusion_sell,financial-inclusion_buy,diversification_obtain,diversification_acquire,question_what,question_when,question_how,question_which,crop_harvest,climate_time,disease_harvest,livestock_livestock,livestock_animals,livestock_sheep,livestock_cattle,livestock_donkey,livestock_pig,livestock_cow,livestock_goat,livestock_camel,livestock_hen,livestock_chicken,livestock_poultry,livestock_bee,diversification_expand,diversification_begin,crop_plant,crop_variety,disease_plant,crop_seed,crop_grow,crop_mulch,diversification_grow,crop_crop,crop_potatoes,crop_passion,crop_maize,crop_banana,crop_coffee,crop_tea,crop_onions,crop_bean,crop_cabbage,climate_rain,diversification_add,question_who,disease_rabbit,diversification_use,crop_tomatoes,crop_rice,disease_disease,disease_care,crop_keep,disease_keep,financial-inclusion_market,financial-inclusion_cost,question_many,crop_layer,disease_treat,disease_prevent,disease_chemical,crop_fruit,livestock_milk,crop_leave,crop_land,disease_leave,livestock_egg,livestock_breed,crop_manure,diversification_increase,climate_season,disease_control,climate_sun,crop_yield,livestock_dairy,crop_soil,diversification_irrigation,diversification_scale,financial-inclusion_money,question_where,diversification_best,disease_spray,disease_turn,disease_attack,financial-inclusion_fee,crop_type,climate_climate,disease_medicine,disease_tick,disease_weed,disease_pests,financial-inclusion_finance,financial-inclusion_investment,financial-inclusion_loan,diversification_new,livestock_lay,climate_heat,climate_drought,diversification_clear,disease_black,disease_space,crop_fertilizer,disease_sick,climate_temperature,climate_flood,disease_affect,financial-inclusion_sum,disease_unhealthy,financial-inclusion_bank,financial-inclusion_insurance,disease_mean,financial-inclusion_credit,diversification_acreage,diversification_diversify,diversification_register,climate_water,diversification_shift,financial-inclusion_economy
0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,1.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1.0,1.0,NaN,NaN,NaN,1.0,1.0,1.0,1.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,1.0,NaN,NaN,NaN,NaN,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,1.0,1.0,NaN,1.0,1.0,NaN,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0,1.0,NaN,1.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
niche_collst = all3.columns[54:173]

In [19]:
all3.iloc[:5, -12:-5]

,financial-inclusion,diversification,question,crop,climate,disease,livestock
0,1.0,1.0,1.0,NaN,NaN,NaN,NaN
1,NaN,NaN,1.0,1.0,1.0,1.0,1.0
2,NaN,1.0,1.0,1.0,NaN,1.0,NaN
4,1.0,1.0,1.0,1.0,1.0,1.0,NaN
8,NaN,1.0,1.0,1.0,NaN,1.0,1.0

In [20]:
broad_collst = all3.columns[-12:-5]

#colors

In [21]:
import plotly.express as px

segment1_color = "#A1A1A1"
segment2_color = "#F9C926"
segment3_color = "#DC7326"
segment4_color = "#4897CD"
segment5_color = "#2E9999"

In [22]:
segment_colors_dct = {
  "1": segment1_color,
  "2": segment2_color,
  "3": segment3_color,
  "4": segment4_color,
  "5": segment5_color
}

# map and pie

In [23]:
vc_country = all3["question_user_country_code"].value_counts()

# segments distribution tab

In [24]:
segmentation_collst = list(segment_user_id_dct.keys())

gb_segments_dct = {}
for segmentation in segmentation_collst:
  gb_segments_dct[segmentation] = all3.groupby([
    "question_user_country_code",
    segmentation
  ]).size().reset_index(name="n")

# topic sums

In [25]:
import numpy as np

gb_country_segment_b_topic_dct = {}
for segmentation in segmentation_collst:
  gb_sum = all3.groupby([
    "question_user_country_code",
    segmentation
  ])[broad_collst].sum()
  gb_count = all3.groupby([
    "question_user_country_code",
    segmentation
  ]).size()
  row_sums = gb_sum[broad_collst].sum(axis=1)
  gb_pct = gb_sum[broad_collst].div(row_sums, axis=0)
  gb_se = np.sqrt(gb_pct * ( 1- gb_pct)).div(np.sqrt(gb_count), axis=0)

  gb_pct = gb_pct.reset_index()
  gb_se = gb_se.reset_index()
  gb_sum = gb_sum.reset_index()

  gb_sum["count"] = gb_count.values

  gb_pct_long = gb_pct.melt(
    id_vars=["question_user_country_code", segmentation],
    value_vars=broad_collst,
    var_name="category",
    value_name="pct"
  )

  gb_se_long = gb_se.melt(
    id_vars=["question_user_country_code", segmentation],
    value_vars=broad_collst,
    var_name="category",
    value_name="se"
  )

  gb_long = gb_pct_long.merge(
    gb_se_long,
    on=["question_user_country_code", segmentation, "category"]
  ).merge(
    gb_sum[["question_user_country_code", segmentation, "count"]],
    on=["question_user_country_code", segmentation]
  ).sort_values(
    by="category"
  )

  gb_long["segment_color"] = gb_long[segmentation].map(segment_colors_dct)

  gb_country_segment_b_topic_dct[segmentation] = gb_long

In [26]:
gb_country_segment_b_topic_dct["user_activity_post_count"]

,question_user_country_code,user_activity_post_count,category,pct,se,count,segment_color
41,KE,2,climate,0.056527,0.000637,131321,#F9C926
48,UG,4,climate,0.048071,0.000384,310612,#4897CD
47,UG,3,climate,0.048781,0.000457,222005,#DC7326
46,UG,2,climate,0.047917,0.000580,135611,#F9C926
40,KE,1,climate,0.054767,0.000457,247890,#A1A1A1
45,UG,1,climate,0.046726,0.000434,236296,#A1A1A1
44,KE,5,climate,0.057686,0.000336,482648,#2E9999
43,KE,4,climate,0.058065,0.000380,377920,#4897CD
42,KE,3,climate,0.057804,0.000495,221901,#DC7326
49,UG,5,climate,0.045607,0.000426,239638,#2E9999
34,KE,5,crop,0.186697,0.000561,482648,#2E9999
31,KE,2,crop,0.191007,0.001085,131321,#F9C926
32,KE,3,crop,0.191087,0.000835,221901,#DC7326
33,KE,4,crop,0.189080,0.000637,377920,#4897CD
35,UG,1,crop,0.203661,0.000828,236296,#A1A1A1
36,UG,2,crop,0.203393,0.001093,135611,#F9C926
37,UG,3,crop,0.201691,0.000852,222005,#DC7326
30,KE,1,crop,0.192219,0.000791,247890,#A1A1A1
38,UG,4,crop,0.201360,0.000720,310612,#4897CD
39,UG,5,crop,0.198302,0.000814,239638,#2E9999
50,KE,1,disease,0.173597,0.000761,247890,#A1A1A1
59,UG,5,disease,0.181026,0.000787,239638,#2E9999
58,UG,4,disease,0.179566,0.000689,310612,#4897CD
57,UG,3,disease,0.179074,0.000814,222005,#DC7326
56,UG,2,disease,0.179061,0.001041,135611,#F9C926
55,UG,1,disease,0.178032,0.000787,236296,#A1A1A1
54,KE,5,disease,0.170741,0.000542,482648,#2E9999
53,KE,4,disease,0.173002,0.000615,377920,#4897CD
52,KE,3,disease,0.174515,0.000806,221901,#DC7326
51,KE,2,disease,0.175213,0.001049,131321,#F9C926
10,KE,1,diversification,0.136220,0.000689,247890,#A1A1A1
11,KE,2,diversification,0.134990,0.000943,131321,#F9C926
12,KE,3,diversification,0.133684,0.000722,221901,#DC7326
13,KE,4,diversification,0.131928,0.000550,377920,#4897CD
14,KE,5,diversification,0.125981,0.000478,482648,#2E9999
15,UG,1,diversification,0.129022,0.000690,236296,#A1A1A1
16,UG,2,diversification,0.128448,0.000909,135611,#F9C926
17,UG,3,diversification,0.127998,0.000709,222005,#DC7326
18,UG,4,diversification,0.126405,0.000596,310612,#4897CD
19,UG,5,diversification,0.122672,0.000670,239638,#2E9999
0,KE,1,financial-inclusion,0.082048,0.000551,247890,#A1A1A1
5,UG,1,financial-inclusion,0.089247,0.000587,236296,#A1A1A1
2,KE,3,financial-inclusion,0.080080,0.000576,221901,#DC7326
6,UG,2,financial-inclusion,0.088255,0.000770,135611,#F9C926
7,UG,3,financial-inclusion,0.088826,0.000604,222005,#DC7326
8,UG,4,financial-inclusion,0.088296,0.000509,310612,#4897CD
9,UG,5,financial-inclusion,0.087718,0.000578,239638,#2E9999
1,KE,2,financial-inclusion,0.079866,0.000748,131321,#F9C926
4,KE,5,financial-inclusion,0.079474,0.000389,482648,#2E9999
3,KE,4,financial-inclusion,0.080410,0.000442,377920,#4897CD
62,KE,3,livestock,0.114027,0.000675,221901,#DC7326
63,KE,4,livestock,0.116797,0.000522,377920,#4897CD
64,KE,5,livestock,0.124200,0.000475,482648,#2E9999
65,UG,1,livestock,0.086358,0.000578,236296,#A1A1A1
66,UG,2,livestock,0.086741,0.000764,135611,#F9C926
67,UG,3,livestock,0.089162,0.000605,222005,#DC7326
61,KE,2,livestock,0.113696,0.000876,131321,#F9C926
60,KE,1,livestock,0.112224,0.000634,247890,#A1A1A1
69,UG,5,livestock,0.099644,0.000612,239638,#2E9999
68,UG,4,livestock,0.091190,0.000517,310612,#4897CD
20,KE,1,question,0.248925,0.000868,247890,#A1A1A1
21,KE,2,question,0.248701,0.001193,131321,#F9C926
22,KE,3,question,0.248803,0.000918,221901,#DC7326
23,KE,4,question,0.250719,0.000705,377920,#4897CD
24,KE,5,question,0.255222,0.000628,482648,#2E9999
25,UG,1,question,0.266955,0.000910,236296,#A1A1A1
26,UG,2,question,0.266186,0.001200,135611,#F9C926
27,UG,3,question,0.264468,0.000936,222005,#DC7326
28,UG,4,question,0.265113,0.000792,310612,#4897CD
29,UG,5,question,0.265030,0.000902,239638,#2E9999

In [27]:
gb_country_segment_n_topic_dct = {}
for segmentation in segmentation_collst:
  gb_sum = all3.groupby([
    "question_user_country_code",
    segmentation
  ])[niche_collst].sum()
  gb_count = all3.groupby([
    "question_user_country_code",
    segmentation
  ]).size()

  row_sums = gb_sum[niche_collst].sum(axis=1)
  gb_pct = gb_sum[niche_collst].div(row_sums, axis=0)
  gb_se = np.sqrt(gb_pct * (1 - gb_pct)).div(np.sqrt(gb_count), axis=0)

  gb_pct = gb_pct.reset_index()
  gb_se = gb_se.reset_index()
  gb_sum = gb_sum.reset_index()

  gb_sum['count'] = gb_count.values

  gb_pct_long = gb_pct.melt(
    id_vars=["question_user_country_code", segmentation],
    value_vars=niche_collst,
    var_name="category",
    value_name="pct"
  )

  gb_se_long = gb_se.melt(
    id_vars=["question_user_country_code", segmentation],
    value_vars=niche_collst,
    var_name="category",
    value_name="se"
  )

  gb_long = gb_pct_long.merge(
    gb_se_long,
    on=["question_user_country_code", segmentation, "category"]
  ).merge(
    gb_sum[["question_user_country_code", segmentation, "count"]],
    on=["question_user_country_code", segmentation]
  )

  gb_long["broad_type"] = gb_long["category"].str.split("_").str[0]
  gb_long["niche"] = gb_long["category"].str.split("_").str[1]

  gb_long = gb_long.sort_values(
      by=["broad_type", "pct", "niche"],
      ascending=[True, False, True]
  )

  gb_long["segment_color"] = gb_long[segmentation].map(segment_colors_dct)

  gb_country_segment_n_topic_dct[segmentation] = gb_long

In [28]:
gb_country_segment_n_topic_dct["user_activity_post_count"]

,question_user_country_code,user_activity_post_count,category,pct,se,count,broad_type,niche,segment_color
102,KE,3,climate_time,0.008287,0.000192,221901,climate,time,#DC7326
101,KE,2,climate_time,0.008126,0.000248,131321,climate,time,#F9C926
103,KE,4,climate_time,0.008113,0.000146,377920,climate,time,#4897CD
100,KE,1,climate_time,0.007991,0.000179,247890,climate,time,#A1A1A1
107,UG,3,climate_time,0.007874,0.000188,222005,climate,time,#DC7326
106,UG,2,climate_time,0.007766,0.000238,135611,climate,time,#F9C926
104,KE,5,climate_time,0.007751,0.000126,482648,climate,time,#2E9999
105,UG,1,climate_time,0.007615,0.000179,236296,climate,time,#A1A1A1
108,UG,4,climate_time,0.007533,0.000155,310612,climate,time,#4897CD
109,UG,5,climate_time,0.006766,0.000167,239638,climate,time,#2E9999
873,KE,4,climate_climate,0.003795,0.000100,377920,climate,climate,#4897CD
872,KE,3,climate_climate,0.003722,0.000129,221901,climate,climate,#DC7326
874,KE,5,climate_climate,0.003669,0.000087,482648,climate,climate,#2E9999
871,KE,2,climate_climate,0.003575,0.000165,131321,climate,climate,#F9C926
870,KE,1,climate_climate,0.003487,0.000118,247890,climate,climate,#A1A1A1
986,UG,2,climate_drought,0.003045,0.000150,135611,climate,drought,#F9C926
988,UG,4,climate_drought,0.002982,0.000098,310612,climate,drought,#4897CD
987,UG,3,climate_drought,0.002965,0.000115,222005,climate,drought,#DC7326
985,UG,1,climate_drought,0.002928,0.000111,236296,climate,drought,#A1A1A1
974,KE,5,climate_heat,0.002925,0.000078,482648,climate,heat,#2E9999
445,UG,1,climate_rain,0.002838,0.000109,236296,climate,rain,#A1A1A1
446,UG,2,climate_rain,0.002802,0.000144,135611,climate,rain,#F9C926
447,UG,3,climate_rain,0.002752,0.000111,222005,climate,rain,#DC7326
989,UG,5,climate_drought,0.002721,0.000106,239638,climate,drought,#2E9999
448,UG,4,climate_rain,0.002683,0.000093,310612,climate,rain,#4897CD
982,KE,3,climate_drought,0.002581,0.000108,221901,climate,drought,#DC7326
973,KE,4,climate_heat,0.002490,0.000081,377920,climate,heat,#4897CD
983,KE,4,climate_drought,0.002484,0.000081,377920,climate,drought,#4897CD
981,KE,2,climate_drought,0.002466,0.000137,131321,climate,drought,#F9C926
980,KE,1,climate_drought,0.002446,0.000099,247890,climate,drought,#A1A1A1
984,KE,5,climate_drought,0.002439,0.000071,482648,climate,drought,#2E9999
449,UG,5,climate_rain,0.002290,0.000098,239638,climate,rain,#2E9999
442,KE,3,climate_rain,0.002264,0.000101,221901,climate,rain,#DC7326
972,KE,3,climate_heat,0.002208,0.000100,221901,climate,heat,#DC7326
440,KE,1,climate_rain,0.002183,0.000094,247890,climate,rain,#A1A1A1
441,KE,2,climate_rain,0.002171,0.000128,131321,climate,rain,#F9C926
711,KE,2,climate_season,0.002160,0.000128,131321,climate,season,#F9C926
712,KE,3,climate_season,0.002128,0.000098,221901,climate,season,#DC7326
443,KE,4,climate_rain,0.002125,0.000075,377920,climate,rain,#4897CD
710,KE,1,climate_season,0.002122,0.000092,247890,climate,season,#A1A1A1
971,KE,2,climate_heat,0.002119,0.000127,131321,climate,heat,#F9C926
713,KE,4,climate_season,0.002005,0.000073,377920,climate,season,#4897CD
878,UG,4,climate_climate,0.001973,0.000080,310612,climate,climate,#4897CD
879,UG,5,climate_climate,0.001956,0.000090,239638,climate,climate,#2E9999
970,KE,1,climate_heat,0.001932,0.000088,247890,climate,heat,#A1A1A1
877,UG,3,climate_climate,0.001918,0.000093,222005,climate,climate,#DC7326
444,KE,5,climate_rain,0.001882,0.000062,482648,climate,rain,#2E9999
714,KE,5,climate_season,0.001873,0.000062,482648,climate,season,#2E9999
717,UG,3,climate_season,0.001850,0.000091,222005,climate,season,#DC7326
716,UG,2,climate_season,0.001827,0.000116,135611,climate,season,#F9C926
718,UG,4,climate_season,0.001821,0.000076,310612,climate,season,#4897CD
715,UG,1,climate_season,0.001805,0.000087,236296,climate,season,#A1A1A1
876,UG,2,climate_climate,0.001789,0.000115,135611,climate,climate,#F9C926
1055,UG,1,climate_flood,0.001761,0.000086,236296,climate,flood,#A1A1A1
1056,UG,2,climate_flood,0.001742,0.000113,135611,climate,flood,#F9C926
734,KE,5,climate_sun,0.001713,0.000060,482648,climate,sun,#2E9999
733,KE,4,climate_sun,0.001708,0.000067,377920,climate,sun,#4897CD
732,KE,3,climate_sun,0.001705,0.000088,221901,climate,sun,#DC7326
1058,UG,4,climate_flood,0.001670,0.000073,310612,climate,flood,#4897CD
1057,UG,3,climate_flood,0.001655,0.000086,222005,climate,flood,#DC7326
875,UG,1,climate_climate,0.001651,0.000084,236296,climate,climate,#A1A1A1
719,UG,5,climate_season,0.001645,0.000083,239638,climate,season,#2E9999
731,KE,2,climate_sun,0.001605,0.000110,131321,climate,sun,#F9C926
730,KE,1,climate_sun,0.001595,0.000080,247890,climate,sun,#A1A1A1
1059,UG,5,climate_flood,0.001586,0.000081,239638,climate,flood,#2E9999
736,UG,2,climate_sun,0.001580,0.000108,135611,climate,sun,#F9C926
738,UG,4,climate_sun,0.001575,0.000071,310612,climate,sun,#4897CD
735,UG,1,climate_sun,0.001550,0.000081,236296,climate,sun,#A1A1A1
1054,KE,5,climate_flood,0.001538,0.000056,482648,climate,flood,#2E9999
737,UG,3,climate_sun,0.001524,0.000083,222005,climate,sun,#DC7326
739,UG,5,climate_sun,0.001509,0.000079,239638,climate,sun,#2E9999
1052,KE,3,climate_flood,0.001493,0.000082,221901,climate,flood,#DC7326
979,UG,5,climate_heat,0.001491,0.000079,239638,climate,heat,#2E9999
1053,KE,4,climate_flood,0.001465,0.000062,377920,climate,flood,#4897CD
1051,KE,2,climate_flood,0.001432,0.000104,131321,climate,flood,#F9C926
1050,KE,1,climate_flood,0.001387,0.000075,247890,climate,flood,#A1A1A1
977,UG,3,climate_heat,0.001358,0.000078,222005,climate,heat,#DC7326
978,UG,4,climate_heat,0.001346,0.000066,310612,climate,heat,#4897CD
976,UG,2,climate_heat,0.001238,0.000095,135611,climate,heat,#F9C926
975,UG,1,climate_heat,0.001140,0.000069,236296,climate,heat,#A1A1A1
1042,KE,3,climate_temperature,0.000959,0.000066,221901,climate,temperature,#DC7326
1044,KE,5,climate_temperature,0.000951,0.000044,482648,climate,temperature,#2E9999
1043,KE,4,climate_temperature,0.000943,0.000050,377920,climate,temperature,#4897CD
1040,KE,1,climate_temperature,0.000936,0.000061,247890,climate,temperature,#A1A1A1
1041,KE,2,climate_temperature,0.000909,0.000083,131321,climate,temperature,#F9C926
1049,UG,5,climate_temperature,0.000667,0.000053,239638,climate,temperature,#2E9999
1048,UG,4,climate_temperature,0.000600,0.000044,310612,climate,temperature,#4897CD
1045,UG,1,climate_temperature,0.000576,0.000049,236296,climate,temperature,#A1A1A1
1047,UG,3,climate_temperature,0.000575,0.000051,222005,climate,temperature,#DC7326
1046,UG,2,climate_temperature,0.000556,0.000064,135611,climate,temperature,#F9C926
1164,KE,5,climate_water,0.000050,0.000010,482648,climate,water,#2E9999
1163,KE,4,climate_water,0.000049,0.000011,377920,climate,water,#4897CD
1160,KE,1,climate_water,0.000039,0.000012,247890,climate,water,#A1A1A1
1162,KE,3,climate_water,0.000037,0.000013,221901,climate,water,#DC7326
1169,UG,5,climate_water,0.000032,0.000012,239638,climate,water,#2E9999
1161,KE,2,climate_water,0.000030,0.000015,131321,climate,water,#F9C926
1168,UG,4,climate_water,0.000028,0.000009,310612,climate,water,#4897CD
1165,UG,1,climate_water,0.000027,0.000011,236296,climate,water,#A1A1A1
1166,UG,2,climate_water,0.000025,0.000013,135611,climate,water,#F9C926
1167,UG,3,climate_water,0.000018,0.000009,222005,climate,water,#DC7326
348,UG,4,crop_crop,0.024729,0.000279,310612,crop,crop,#4897CD
347,UG,3,crop_crop,0.024538,0.000328,222005,crop,crop,#DC7326
346,UG,2,crop_crop,0.024444,0.000419,135611,crop,crop,#F9C926
345,UG,1,crop_crop,0.024397,0.000317,236296,crop,crop,#A1A1A1
428,UG,4,crop_bean,0.023947,0.000274,310612,crop,bean,#4897CD
398,UG,4,crop_coffee,0.023684,0.000273,310612,crop,coffee,#4897CD
425,UG,1,crop_bean,0.023676,0.000313,236296,crop,bean,#A1A1A1
349,UG,5,crop_crop,0.023656,0.000310,239638,crop,crop,#2E9999
429,UG,5,crop_bean,0.023572,0.000310,239638,crop,bean,#2E9999
427,UG,3,crop_bean,0.023513,0.000322,222005,crop,bean,#DC7326
408,UG,4,crop_tea,0.023400,0.000271,310612,crop,tea,#4897CD
399,UG,5,crop_coffee,0.023380,0.000309,239638,crop,coffee,#2E9999
426,UG,2,crop_bean,0.023365,0.000410,135611,crop,bean,#F9C926
395,UG,1,crop_coffee,0.023311,0.000310,236296,crop,coffee,#A1A1A1
397,UG,3,crop_coffee,0.023287,0.000320,222005,crop,coffee,#DC7326
407,UG,3,crop_tea,0.023247,0.000320,222005,crop,tea,#DC7326
396,UG,2,crop_coffee,0.023182,0.000409,135611,crop,coffee,#F9C926
409,UG,5,crop_tea,0.022972,0.000306,239638,crop,tea,#2E9999
405,UG,1,crop_tea,0.022833,0.000307,236296,crop,tea,#A1A1A1
406,UG,2,crop_tea,0.022714,0.000405,135611,crop,tea,#F9C926
341,KE,2,crop_crop,0.020286,0.000389,131321,crop,crop,#F9C926
342,KE,3,crop_crop,0.020283,0.000299,221901,crop,crop,#DC7326
343,KE,4,crop_crop,0.020139,0.000229,377920,crop,crop,#4897CD
340,KE,1,crop_crop,0.019879,0.000280,247890,crop,crop,#A1A1A1
403,KE,4,crop_tea,0.019878,0.000227,377920,crop,tea,#4897CD
498,UG,4,crop_tomatoes,0.019631,0.000249,310612,crop,tomatoes,#4897CD
377,UG,3,crop_maize,0.019537,0.000294,222005,crop,maize,#DC7326
401,KE,2,crop_tea,0.019529,0.000382,131321,crop,tea,#F9C926
402,KE,3,crop_tea,0.019504,0.000294,221901,crop,tea,#DC7326
344,KE,5,crop_crop,0.019426,0.000199,482648,crop,crop,#2E9999
497,UG,3,crop_tomatoes,0.019272,0.000292,222005,crop,tomatoes,#DC7326
376,UG,2,crop_maize,0.019259,0.000373,135611,crop,maize,#F9C926
496,UG,2,crop_tomatoes,0.019259,0.000373,135611,crop,tomatoes,#F9C926
404,KE,5,crop_tea,0.019227,0.000198,482648,crop,tea,#2E9999
400,KE,1,crop_tea,0.019182,0.000275,247890,crop,tea,#A1A1A1
495,UG,1,crop_tomatoes,0.019158,0.000282,236296,crop,tomatoes,#A1A1A1
375,UG,1,crop_maize,0.019156,0.000282,236296,crop,maize,#A1A1A1
378,UG,4,crop_maize,0.019060,0.000245,310612,crop,maize,#4897CD
423,KE,4,crop_bean,0.018711,0.000220,377920,crop,bean,#4897CD
424,KE,5,crop_bean,0.018648,0.000195,482648,crop,bean,#2E9999
422,KE,3,crop_bean,0.018629,0.000287,221901,crop,bean,#DC7326
499,UG,5,crop_tomatoes,0.018418,0.000275,239638,crop,tomatoes,#2E9999
421,KE,2,crop_bean,0.018410,0.000371,131321,crop,bean,#F9C926
420,KE,1,crop_bean,0.018214,0.000269,247890,crop,bean,#A1A1A1
388,UG,4,crop_banana,0.018055,0.000239,310612,crop,banana,#4897CD
379,UG,5,crop_maize,0.018012,0.000272,239638,crop,maize,#2E9999
353,KE,4,crop_potatoes,0.017709,0.000215,377920,crop,potatoes,#4897CD
385,UG,1,crop_banana,0.017680,0.000271,236296,crop,banana,#A1A1A1
351,KE,2,crop_potatoes,0.017673,0.000364,131321,crop,potatoes,#F9C926
352,KE,3,crop_potatoes,0.017649,0.000280,221901,crop,potatoes,#DC7326
387,UG,3,crop_banana,0.017536,0.000279,222005,crop,banana,#DC7326
358,UG,4,crop_potatoes,0.017524,0.000235,310612,crop,potatoes,#4897CD
389,UG,5,crop_banana,0.017479,0.000268,239638,crop,banana,#2E9999
350,KE,1,crop_potatoes,0.017431,0.000263,247890,crop,potatoes,#A1A1A1
493,KE,4,crop_tomatoes,0.017428,0.000213,377920,crop,tomatoes,#4897CD
386,UG,2,crop_banana,0.017363,0.000355,135611,crop,banana,#F9C926
357,UG,3,crop_potatoes,0.017296,0.000277,222005,crop,potatoes,#DC7326
508,UG,4,crop_rice,0.017273,0.000234,310612,crop,rice,#4897CD
492,KE,3,crop_tomatoes,0.017232,0.000276,221901,crop,tomatoes,#DC7326
355,UG,1,crop_potatoes,0.017212,0.000268,236296,crop,potatoes,#A1A1A1
393,KE,4,crop_coffee,0.017177,0.000211,377920,crop,coffee,#4897CD
356,UG,2,crop_potatoes,0.017168,0.000353,135611,crop,potatoes,#F9C926
491,KE,2,crop_tomatoes,0.017074,0.000357,131321,crop,tomatoes,#F9C926
394,KE,5,crop_coffee,0.017073,0.000186,482648,crop,coffee,#2E9999
354,KE,5,crop_potatoes,0.017044,0.000186,482648,crop,potatoes,#2E9999
490,KE,1,crop_tomatoes,0.016950,0.000259,247890,crop,tomatoes,#A1A1A1
392,KE,3,crop_coffee,0.016877,0.000273,221901,crop,coffee,#DC7326
494,KE,5,crop_tomatoes,0.016851,0.000185,482648,crop,tomatoes,#2E9999
506,UG,2,crop_rice,0.016791,0.000349,135611,crop,rice,#F9C926
505,UG,1,crop_rice,0.016756,0.000264,236296,crop,rice,#A1A1A1
391,KE,2,crop_coffee,0.016701,0.000354,131321,crop,coffee,#F9C926
359,UG,5,crop_potatoes,0.016629,0.000261,239638,crop,potatoes,#2E9999
507,UG,3,crop_rice,0.016528,0.000271,222005,crop,rice,#DC7326
390,KE,1,crop_coffee,0.016484,0.000256,247890,crop,coffee,#A1A1A1
509,UG,5,crop_rice,0.016299,0.000259,239638,crop,rice,#2E9999
300,KE,1,crop_seed,0.015435,0.000248,247890,crop,seed,#A1A1A1
302,KE,3,crop_seed,0.015413,0.000262,221901,crop,seed,#DC7326
301,KE,2,crop_seed,0.015311,0.000339,131321,crop,seed,#F9C926
303,KE,4,crop_seed,0.015259,0.000199,377920,crop,seed,#4897CD
91,KE,2,crop_harvest,0.014786,0.000333,131321,crop,harvest,#F9C926
92,KE,3,crop_harvest,0.014773,0.000256,221901,crop,harvest,#DC7326
90,KE,1,crop_harvest,0.014668,0.000241,247890,crop,harvest,#A1A1A1
371,KE,2,crop_maize,0.014540,0.000330,131321,crop,maize,#F9C926
373,KE,4,crop_maize,0.014491,0.000194,377920,crop,maize,#4897CD
93,KE,4,crop_harvest,0.014490,0.000194,377920,crop,harvest,#4897CD
384,KE,5,crop_banana,0.014303,0.000171,482648,crop,banana,#2E9999
304,KE,5,crop_seed,0.014279,0.000171,482648,crop,seed,#2E9999
372,KE,3,crop_maize,0.014275,0.000252,221901,crop,maize,#DC7326
275,UG,1,crop_plant,0.014267,0.000244,236296,crop,plant,#A1A1A1
383,KE,4,crop_banana,0.014246,0.000193,377920,crop,banana,#4897CD
276,UG,2,crop_plant,0.014237,0.000322,135611,crop,plant,#F9C926
326,UG,2,crop_mulch,0.014067,0.000320,135611,crop,mulch,#F9C926
325,UG,1,crop_mulch,0.014058,0.000242,236296,crop,mulch,#A1A1A1
370,KE,1,crop_maize,0.013930,0.000235,247890,crop,maize,#A1A1A1
382,KE,3,crop_banana,0.013918,0.000249,221901,crop,banana,#DC7326
277,UG,3,crop_plant,0.013897,0.000248,222005,crop,plant,#DC7326
322,KE,3,crop_mulch,0.013824,0.000248,221901,crop,mulch,#DC7326
327,UG,3,crop_mulch,0.013802,0.000248,222005,crop,mulch,#DC7326
320,KE,1,crop_mulch,0.013780,0.000234,247890,crop,mulch,#A1A1A1
381,KE,2,crop_banana,0.013764,0.000322,131321,crop,banana,#F9C926
96,UG,2,crop_harvest,0.013748,0.000316,135611,crop,harvest,#F9C926
321,KE,2,crop_mulch,0.013739,0.000321,131321,crop,mulch,#F9C926
95,UG,1,crop_harvest,0.013672,0.000239,236296,crop,harvest,#A1A1A1
312,KE,3,crop_grow,0.013652,0.000246,221901,crop,grow,#DC7326
380,KE,1,crop_banana,0.013620,0.000233,247890,crop,banana,#A1A1A1
328,UG,4,crop_mulch,0.013610,0.000208,310612,crop,mulch,#4897CD
374,KE,5,crop_maize,0.013606,0.000167,482648,crop,maize,#2E9999
311,KE,2,crop_grow,0.013583,0.000319,131321,crop,grow,#F9C926
97,UG,3,crop_harvest,0.013548,0.000245,222005,crop,harvest,#DC7326
310,KE,1,crop_grow,0.013519,0.000232,247890,crop,grow,#A1A1A1
278,UG,4,crop_plant,0.013510,0.000207,310612,crop,plant,#4897CD
94,KE,5,crop_harvest,0.013474,0.000166,482648,crop,harvest,#2E9999
313,KE,4,crop_grow,0.013438,0.000187,377920,crop,grow,#4897CD
580,KE,1,crop_layer,0.013383,0.000231,247890,crop,layer,#A1A1A1
98,UG,4,crop_harvest,0.013368,0.000206,310612,crop,harvest,#4897CD
323,KE,4,crop_mulch,0.013368,0.000187,377920,crop,mulch,#4897CD
307,UG,3,crop_seed,0.013110,0.000241,222005,crop,seed,#DC7326
306,UG,2,crop_seed,0.013081,0.000309,135611,crop,seed,#F9C926
305,UG,1,crop_seed,0.013045,0.000233,236296,crop,seed,#A1A1A1
308,UG,4,crop_seed,0.012981,0.000203,310612,crop,seed,#4897CD
329,UG,5,crop_mulch,0.012908,0.000231,239638,crop,mulch,#2E9999
316,UG,2,crop_grow,0.012892,0.000306,135611,crop,grow,#F9C926
315,UG,1,crop_grow,0.012803,0.000231,236296,crop,grow,#A1A1A1
99,UG,5,crop_harvest,0.012745,0.000229,239638,crop,harvest,#2E9999
317,UG,3,crop_grow,0.012692,0.000238,222005,crop,grow,#DC7326
314,KE,5,crop_grow,0.012595,0.000161,482648,crop,grow,#2E9999
318,UG,4,crop_grow,0.012591,0.000200,310612,crop,grow,#4897CD
581,KE,2,crop_layer,0.012523,0.000307,131321,crop,layer,#F9C926
324,KE,5,crop_mulch,0.012506,0.000160,482648,crop,mulch,#2E9999
279,UG,5,crop_plant,0.012377,0.000226,239638,crop,plant,#2E9999
309,UG,5,crop_seed,0.012318,0.000225,239638,crop,seed,#2E9999
655,UG,1,crop_land,0.012296,0.000227,236296,crop,land,#A1A1A1
582,KE,3,crop_layer,0.012247,0.000233,221901,crop,layer,#DC7326
656,UG,2,crop_land,0.012195,0.000298,135611,crop,land,#F9C926
319,UG,5,crop_grow,0.011896,0.000221,239638,crop,grow,#2E9999
657,UG,3,crop_land,0.011780,0.000229,222005,crop,land,#DC7326
504,KE,5,crop_rice,0.011766,0.000155,482648,crop,rice,#2E9999
502,KE,3,crop_rice,0.011563,0.000227,221901,crop,rice,#DC7326
503,KE,4,crop_rice,0.011508,0.000173,377920,crop,rice,#4897CD
500,KE,1,crop_rice,0.011390,0.000213,247890,crop,rice,#A1A1A1
583,KE,4,crop_layer,0.011305,0.000172,377920,crop,layer,#4897CD
501,KE,2,crop_rice,0.011301,0.000292,131321,crop,rice,#F9C926
584,KE,5,crop_layer,0.011300,0.000152,482648,crop,layer,#2E9999
658,UG,4,crop_land,0.011299,0.000190,310612,crop,land,#4897CD
271,KE,2,crop_plant,0.011290,0.000292,131321,crop,plant,#F9C926
411,KE,2,crop_onions,0.011274,0.000291,131321,crop,onions,#F9C926
270,KE,1,crop_plant,0.011274,0.000212,247890,crop,plant,#A1A1A1
413,KE,4,crop_onions,0.011224,0.000171,377920,crop,onions,#4897CD
272,KE,3,crop_plant,0.011110,0.000223,221901,crop,plant,#DC7326
412,KE,3,crop_onions,0.010985,0.000221,221901,crop,onions,#DC7326
273,KE,4,crop_plant,0.010797,0.000168,377920,crop,plant,#4897CD
659,UG,5,crop_land,0.010764,0.000211,239638,crop,land,#2E9999
410,KE,1,crop_onions,0.010644,0.000206,247890,crop,onions,#A1A1A1
417,UG,3,crop_onions,0.010478,0.000216,222005,crop,onions,#DC7326
433,KE,4,crop_cabbage,0.010272,0.000164,377920,crop,cabbage,#4897CD
431,KE,2,crop_cabbage,0.010188,0.000277,131321,crop,cabbage,#F9C926
414,KE,5,crop_onions,0.010076,0.000144,482648,crop,onions,#2E9999
432,KE,3,crop_cabbage,0.010064,0.000212,221901,crop,cabbage,#DC7326
650,KE,1,crop_land,0.010051,0.000200,247890,crop,land,#A1A1A1
415,UG,1,crop_onions,0.010043,0.000205,236296,crop,onions,#A1A1A1
416,UG,2,crop_onions,0.010035,0.000271,135611,crop,onions,#F9C926
418,UG,4,crop_onions,0.009990,0.000178,310612,crop,onions,#4897CD
274,KE,5,crop_plant,0.009809,0.000142,482648,crop,plant,#2E9999
430,KE,1,crop_cabbage,0.009749,0.000197,247890,crop,cabbage,#A1A1A1
283,KE,4,crop_variety,0.009515,0.000158,377920,crop,variety,#4897CD
282,KE,3,crop_variety,0.009483,0.000206,221901,crop,variety,#DC7326
651,KE,2,crop_land,0.009456,0.000267,131321,crop,land,#F9C926
419,UG,5,crop_onions,0.009385,0.000197,239638,crop,onions,#2E9999
437,UG,3,crop_cabbage,0.009366,0.000204,222005,crop,cabbage,#DC7326
281,KE,2,crop_variety,0.009353,0.000266,131321,crop,variety,#F9C926
434,KE,5,crop_cabbage,0.009275,0.000138,482648,crop,cabbage,#2E9999
652,KE,3,crop_land,0.009227,0.000203,221901,crop,land,#DC7326
280,KE,1,crop_variety,0.009162,0.000191,247890,crop,variety,#A1A1A1
284,KE,5,crop_variety,0.009104,0.000137,482648,crop,variety,#2E9999
435,UG,1,crop_cabbage,0.009037,0.000195,236296,crop,cabbage,#A1A1A1
286,UG,2,crop_variety,0.008915,0.000255,135611,crop,variety,#F9C926
653,KE,4,crop_land,0.008880,0.000153,377920,crop,land,#4897CD
436,UG,2,crop_cabbage,0.008878,0.000255,135611,crop,cabbage,#F9C926
438,UG,4,crop_cabbage,0.008786,0.000167,310612,crop,cabbage,#4897CD
285,UG,1,crop_variety,0.008738,0.000191,236296,crop,variety,#A1A1A1
654,KE,5,crop_land,0.008681,0.000134,482648,crop,land,#2E9999
287,UG,3,crop_variety,0.008654,0.000197,222005,crop,variety,#DC7326
289,UG,5,crop_variety,0.008571,0.000188,239638,crop,variety,#2E9999
288,UG,4,crop_variety,0.008537,0.000165,310612,crop,variety,#4897CD
589,UG,5,crop_layer,0.008400,0.000186,239638,crop,layer,#2E9999
439,UG,5,crop_cabbage,0.008357,0.000186,239638,crop,cabbage,#2E9999
588,UG,4,crop_layer,0.008268,0.000162,310612,crop,layer,#4897CD
585,UG,1,crop_layer,0.007940,0.000183,236296,crop,layer,#A1A1A1
587,UG,3,crop_layer,0.007894,0.000188,222005,crop,layer,#DC7326
586,UG,2,crop_layer,0.007820,0.000239,135611,crop,layer,#F9C926
769,UG,5,crop_soil,0.006538,0.000165,239638,crop,soil,#2E9999
766,UG,2,crop_soil,0.006275,0.000214,135611,crop,soil,#F9C926
768,UG,4,crop_soil,0.006153,0.000140,310612,crop,soil,#4897CD
767,UG,3,crop_soil,0.006117,0.000165,222005,crop,soil,#DC7326
367,UG,3,crop_passion,0.006106,0.000165,222005,crop,passion,#DC7326
765,UG,1,crop_soil,0.006075,0.000160,236296,crop,soil,#A1A1A1
365,UG,1,crop_passion,0.005788,0.000156,236296,crop,passion,#A1A1A1

In [29]:
# gb_country_segment_n_topic_dct = {}
# for segmentation in segmentation_collst:
#   gb = all3.groupby([
#     "question_user_country_code",
#     segmentation
#   ])[niche_collst].sum().reset_index()

#   row_sums = gb[niche_collst].sum(axis=1)
#   gb[niche_collst] = gb[niche_collst].div(row_sums, axis=0)

#   gb_long = gb.melt(
#     id_vars=["question_user_country_code", segmentation],
#     value_vars=gb.columns[2:],
#     var_name="category",
#     value_name="pct"
#   )

#   gb_long["broad_type"] = gb_long["category"].str.split("_").str[0]
#   gb_long["niche"] = gb_long["category"].str.split("_").str[1]

#   gb_long = gb_long.sort_values(
#     by=["broad_type", "pct", "niche"],
#     ascending=[True, False, True]
#   )

#   gb_long["segment_color"] = gb_long[segmentation].map(segment_colors_dct)

#   gb_country_segment_n_topic_dct[segmentation] = gb_long

#time slices

In [30]:
time_collst = [
  "question_set_dt_year",
  "question_set_dt_month",
  "question_set_dt_hour",
  "question_set_dt_day_of_week"
]

In [40]:
gb_country_segment_b_topic_time_dct = defaultdict(dict)
for segmentation in segmentation_collst:
  for time in time_collst:
    gb_sum = all3.groupby([
      "question_user_country_code",
      segmentation,
      time
    ])[broad_collst].sum()

    gb_count = all3.groupby([
      "question_user_country_code",
      segmentation,
      time
    ]).size()

    row_sums = gb_sum[broad_collst].sum(axis=1)
    gb_pct = gb_sum[broad_collst].div(row_sums, axis=0)
    gb_se = np.sqrt(gb_pct * (1 - gb_pct)).div(np.sqrt(gb_count), axis=0)

    gb_pct = gb_pct.reset_index()
    gb_se = gb_se.reset_index()
    gb_sum = gb_sum.reset_index()
    gb_sum['count'] = gb_count.values

    gb_pct_long = gb_pct.melt(
      id_vars=["question_user_country_code", segmentation, time],
      value_vars=broad_collst,
      var_name="category",
      value_name="pct"
    )

    gb_se_long = gb_se.melt(
      id_vars=["question_user_country_code", segmentation, time],
      value_vars=broad_collst,
      var_name="category",
      value_name="se"
    )

    gb_long = gb_pct_long.merge(
      gb_se_long,
      on=["question_user_country_code", segmentation, time, "category"]
    ).merge(
      gb_sum[["question_user_country_code", segmentation, time, "count"]],
      on=["question_user_country_code", segmentation, time]
    ).sort_values(
      by=time,
      ascending=False
    )

    gb_long["segment_color"] = gb_long[segmentation].map(segment_colors_dct)

    gb_country_segment_b_topic_time_dct[segmentation][time] = gb_long

In [32]:
# gb_country_segment_b_topic_time_dct = defaultdict(dict)
# for segmentation in segmentation_collst:
#   for time in time_collst:
#     gb = all3.groupby([
#       "question_user_country_code",
#       segmentation,
#       time
#     ])[broad_collst].sum().reset_index()

#     row_sums = gb[broad_collst].sum(axis=1)
#     gb[broad_collst ] = gb[broad_collst].div(row_sums, axis=0)

#     gb_long = gb.melt(
#       id_vars=["question_user_country_code", segmentation, time],
#       value_vars=gb.columns[2:],
#       var_name="category",
#       value_name="pct"
#     )

#     gb_long["segment_color"] = gb_long[segmentation].map(segment_colors_dct)

#     gb_country_segment_b_topic_time_dct[segmentation][time] = gb_long

In [33]:
gb_country_segment_b_topic_time_dct["speed_post_response"]["question_set_dt_year"]

,question_user_country_code,speed_post_response,question_set_dt_year,category,pct,se,count,segment_color
0,KE,1,2017,financial-inclusion,0.102541,0.005497,3046,#A1A1A1
35,UG,2,2017,financial-inclusion,0.090620,0.006287,2085,#F9C926
45,UG,4,2017,financial-inclusion,0.107625,0.010856,815,#4897CD
40,UG,3,2017,financial-inclusion,0.095777,0.006309,2176,#DC7326
55,KE,1,2017,diversification,0.125742,0.006008,3046,#A1A1A1
50,UG,5,2017,financial-inclusion,0.105479,0.012287,625,#2E9999
325,UG,5,2017,disease,0.183562,0.015485,625,#2E9999
61,KE,2,2017,diversification,0.131825,0.006185,2992,#F9C926
330,KE,1,2017,livestock,0.128575,0.006065,3046,#A1A1A1
336,KE,2,2017,livestock,0.129903,0.006146,2992,#F9C926
342,KE,3,2017,livestock,0.129965,0.005197,4187,#DC7326
85,UG,1,2017,diversification,0.125067,0.006404,2668,#A1A1A1
79,KE,5,2017,diversification,0.133488,0.008644,1548,#2E9999
73,KE,4,2017,diversification,0.134400,0.009132,1395,#4897CD
67,KE,3,2017,diversification,0.134160,0.005267,4187,#DC7326
348,KE,4,2017,livestock,0.133480,0.009106,1395,#4897CD
90,UG,2,2017,diversification,0.123498,0.007205,2085,#F9C926
95,UG,3,2017,diversification,0.124589,0.007080,2176,#DC7326
293,KE,4,2017,disease,0.174113,0.010153,1395,#4897CD
299,KE,5,2017,disease,0.169007,0.009525,1548,#2E9999
305,UG,1,2017,disease,0.175349,0.007362,2668,#A1A1A1
310,UG,2,2017,disease,0.181793,0.008446,2085,#F9C926
265,UG,4,2017,climate,0.054656,0.007962,815,#4897CD
260,UG,3,2017,climate,0.044336,0.004413,2176,#DC7326
116,KE,2,2017,question,0.230890,0.007704,2992,#F9C926
122,KE,3,2017,question,0.227486,0.006479,4187,#DC7326
128,KE,4,2017,question,0.223387,0.011152,1395,#4897CD
110,KE,1,2017,question,0.235190,0.007685,3046,#A1A1A1
105,UG,5,2017,diversification,0.125571,0.013255,625,#2E9999
100,UG,4,2017,diversification,0.125506,0.011605,815,#4897CD
320,UG,4,2017,disease,0.172740,0.013242,815,#4897CD
315,UG,3,2017,disease,0.181950,0.008271,2176,#DC7326
275,KE,1,2017,disease,0.169220,0.006794,3046,#A1A1A1
281,KE,2,2017,disease,0.169826,0.006864,2992,#F9C926
287,KE,3,2017,disease,0.173884,0.005857,4187,#DC7326
134,KE,5,2017,question,0.224186,0.010600,1548,#2E9999
140,UG,1,2017,question,0.247896,0.008360,2668,#A1A1A1
270,UG,5,2017,climate,0.035160,0.007367,625,#2E9999
150,UG,3,2017,question,0.249836,0.009281,2176,#DC7326
145,UG,2,2017,question,0.252659,0.009516,2085,#F9C926
226,KE,2,2017,climate,0.055124,0.004172,2992,#F9C926
155,UG,4,2017,question,0.245951,0.015085,815,#4897CD
232,KE,3,2017,climate,0.051567,0.003418,4187,#DC7326
160,UG,5,2017,question,0.252968,0.017389,625,#2E9999
24,KE,5,2017,financial-inclusion,0.106889,0.007853,1548,#2E9999
30,UG,1,2017,financial-inclusion,0.105998,0.005960,2668,#A1A1A1
12,KE,3,2017,financial-inclusion,0.099186,0.004619,4187,#DC7326
6,KE,2,2017,financial-inclusion,0.098104,0.005438,2992,#F9C926
200,UG,2,2017,crop,0.210941,0.008935,2085,#F9C926
205,UG,3,2017,crop,0.204710,0.008650,2176,#DC7326
210,UG,4,2017,crop,0.209852,0.014264,815,#4897CD
215,UG,5,2017,crop,0.217352,0.016498,625,#2E9999
220,KE,1,2017,climate,0.052599,0.004045,3046,#A1A1A1
18,KE,4,2017,financial-inclusion,0.097996,0.007960,1395,#4897CD
195,UG,1,2017,crop,0.211995,0.007913,2668,#A1A1A1
189,KE,5,2017,crop,0.189162,0.009954,1548,#2E9999
171,KE,2,2017,crop,0.184328,0.007089,2992,#F9C926
177,KE,3,2017,crop,0.183753,0.005985,4187,#DC7326
183,KE,4,2017,crop,0.186064,0.010419,1395,#4897CD
165,KE,1,2017,crop,0.186133,0.007052,3046,#A1A1A1
255,UG,2,2017,climate,0.051665,0.004848,2085,#F9C926
250,UG,1,2017,climate,0.051028,0.004260,2668,#A1A1A1
244,KE,5,2017,climate,0.044771,0.005256,1548,#2E9999
238,KE,4,2017,climate,0.050561,0.005866,1395,#4897CD
354,KE,5,2017,livestock,0.132496,0.008617,1548,#2E9999
360,UG,1,2017,livestock,0.082668,0.005331,2668,#A1A1A1
365,UG,2,2017,livestock,0.088824,0.006230,2085,#F9C926
370,UG,3,2017,livestock,0.098803,0.006397,2176,#DC7326
375,UG,4,2017,livestock,0.083671,0.009699,815,#4897CD
380,UG,5,2017,livestock,0.079909,0.010846,625,#2E9999
151,UG,3,2018,question,0.259571,0.001447,91739,#DC7326
288,KE,3,2018,disease,0.172669,0.000855,195424,#DC7326
233,KE,3,2018,climate,0.056223,0.000521,195424,#DC7326
227,KE,2,2018,climate,0.056661,0.000601,148157,#F9C926
156,UG,4,2018,question,0.257949,0.002485,31008,#4897CD
146,UG,2,2018,question,0.261335,0.001732,64325,#F9C926
111,KE,1,2018,question,0.251642,0.001227,125094,#A1A1A1
106,UG,5,2018,diversification,0.127233,0.002616,16229,#2E9999
316,UG,3,2018,disease,0.181129,0.001272,91739,#DC7326
311,UG,2,2018,disease,0.182427,0.001523,64325,#F9C926
271,UG,5,2018,climate,0.045257,0.001632,16229,#2E9999
266,UG,4,2018,climate,0.043733,0.001161,31008,#4897CD
261,UG,3,2018,climate,0.045088,0.000685,91739,#DC7326
117,KE,2,2018,question,0.253576,0.001130,148157,#F9C926
123,KE,3,2018,question,0.250562,0.000980,195424,#DC7326
326,UG,5,2018,disease,0.180724,0.003020,16229,#2E9999
216,UG,5,2018,crop,0.215090,0.003225,16229,#2E9999
1,KE,1,2018,financial-inclusion,0.084218,0.000785,125094,#A1A1A1
201,UG,2,2018,crop,0.210825,0.001608,64325,#F9C926
211,UG,4,2018,crop,0.212464,0.002323,31008,#4897CD
206,UG,3,2018,crop,0.211314,0.001348,91739,#DC7326
25,KE,5,2018,financial-inclusion,0.081315,0.001193,52506,#2E9999
7,KE,2,2018,financial-inclusion,0.080152,0.000705,148157,#F9C926
13,KE,3,2018,financial-inclusion,0.080621,0.000616,195424,#DC7326
19,KE,4,2018,financial-inclusion,0.078771,0.000978,75915,#4897CD
31,UG,1,2018,financial-inclusion,0.091126,0.001085,70415,#A1A1A1
172,KE,2,2018,crop,0.189121,0.001017,148157,#F9C926
178,KE,3,2018,crop,0.189094,0.000886,195424,#DC7326
221,KE,1,2018,climate,0.055886,0.000649,125094,#A1A1A1
190,KE,5,2018,crop,0.189127,0.001709,52506,#2E9999
184,KE,4,2018,crop,0.188304,0.001419,75915,#4897CD
196,UG,1,2018,crop,0.209472,0.001534,70415,#A1A1A1
282,KE,2,2018,disease,0.171392,0.000979,148157,#F9C926
276,KE,1,2018,disease,0.170313,0.001063,125094,#A1A1A1
141,UG,1,2018,question,0.260055,0.001653,70415,#A1A1A1
129,KE,4,2018,question,0.250772,0.001573,75915,#4897CD
135,KE,5,2018,question,0.247870,0.001884,52506,#2E9999
101,UG,4,2018,diversification,0.126907,0.001890,31008,#4897CD
86,UG,1,2018,diversification,0.123447,0.001240,70415,#A1A1A1
74,KE,4,2018,diversification,0.130915,0.001224,75915,#4897CD
68,KE,3,2018,diversification,0.129936,0.000761,195424,#DC7326
349,KE,4,2018,livestock,0.121863,0.001187,75915,#4897CD
306,UG,1,2018,disease,0.180546,0.001450,70415,#A1A1A1
300,KE,5,2018,disease,0.174203,0.001655,52506,#2E9999
96,UG,3,2018,diversification,0.125395,0.001093,91739,#DC7326
91,UG,2,2018,diversification,0.122703,0.001294,64325,#F9C926
294,KE,4,2018,disease,0.173215,0.001373,75915,#4897CD
80,KE,5,2018,diversification,0.131883,0.001477,52506,#2E9999
321,UG,4,2018,disease,0.183222,0.002197,31008,#4897CD
62,KE,2,2018,diversification,0.128684,0.000870,148157,#F9C926
343,KE,3,2018,livestock,0.120895,0.000737,195424,#DC7326
337,KE,2,2018,livestock,0.120414,0.000846,148157,#F9C926
331,KE,1,2018,livestock,0.121059,0.000922,125094,#A1A1A1
51,UG,5,2018,financial-inclusion,0.091690,0.002265,16229,#2E9999
56,KE,1,2018,diversification,0.128670,0.000947,125094,#A1A1A1
46,UG,4,2018,financial-inclusion,0.087280,0.001603,31008,#4897CD
41,UG,3,2018,financial-inclusion,0.088912,0.000940,91739,#DC7326
36,UG,2,2018,financial-inclusion,0.087602,0.001115,64325,#F9C926
355,KE,5,2018,livestock,0.122727,0.001432,52506,#2E9999
366,UG,2,2018,livestock,0.090067,0.001129,64325,#F9C926
371,UG,3,2018,livestock,0.088592,0.000938,91739,#DC7326
376,UG,4,2018,livestock,0.088445,0.001612,31008,#4897CD
381,UG,5,2018,livestock,0.084988,0.002189,16229,#2E9999
361,UG,1,2018,livestock,0.089728,0.001077,70415,#A1A1A1
245,KE,5,2018,climate,0.052875,0.000977,52506,#2E9999
239,KE,4,2018,climate,0.056160,0.000836,75915,#4897CD
166,KE,1,2018,crop,0.188212,0.001105,125094,#A1A1A1
256,UG,2,2018,climate,0.045041,0.000818,64325,#F9C926
251,UG,1,2018,climate,0.045627,0.000786,70415,#A1A1A1
161,UG,5,2018,question,0.255018,0.003421,16229,#2E9999
283,KE,2,2019,disease,0.172995,0.001227,95041,#F9C926
272,UG,5,2019,climate,0.047836,0.001364,24485,#2E9999
130,KE,4,2019,question,0.255274,0.001755,61710,#4897CD
136,KE,5,2019,question,0.253319,0.001878,53620,#2E9999
228,KE,2,2019,climate,0.058625,0.000762,95041,#F9C926
157,UG,4,2019,question,0.262577,0.002161,41463,#4897CD
147,UG,2,2019,question,0.262575,0.001797,59931,#F9C926
152,UG,3,2019,question,0.261971,0.001388,100324,#DC7326
142,UG,1,2019,question,0.261748,0.001586,76817,#A1A1A1
277,KE,1,2019,disease,0.172353,0.001226,94916,#A1A1A1
350,KE,4,2019,livestock,0.115163,0.001285,61710,#4897CD
69,KE,3,2019,diversification,0.131229,0.000948,126840,#DC7326
87,UG,1,2019,diversification,0.127381,0.001203,76817,#A1A1A1
81,KE,5,2019,diversification,0.135826,0.001480,53620,#2E9999
75,KE,4,2019,diversification,0.132118,0.001363,61710,#4897CD
92,UG,2,2019,diversification,0.125083,0.001351,59931,#F9C926
289,KE,3,2019,disease,0.174731,0.001066,126840,#DC7326
295,KE,4,2019,disease,0.175678,0.001532,61710,#4897CD
301,KE,5,2019,disease,0.175919,0.001644,53620,#2E9999
307,UG,1,2019,disease,0.183252,0.001396,76817,#A1A1A1
338,KE,2,2019,livestock,0.117253,0.001044,95041,#F9C926
332,KE,1,2019,livestock,0.118124,0.001048,94916,#A1A1A1
322,UG,4,2019,disease,0.184664,0.001906,41463,#4897CD
327,UG,5,2019,disease,0.184313,0.002478,24485,#2E9999
63,KE,2,2019,diversification,0.128220,0.001084,95041,#F9C926
47,UG,4,2019,financial-inclusion,0.080580,0.001337,41463,#4897CD
52,UG,5,2019,financial-inclusion,0.083192,0.001765,24485,#2E9999
57,KE,1,2019,diversification,0.129352,0.001089,94916,#A1A1A1
42,UG,3,2019,financial-inclusion,0.081690,0.000865,100324,#DC7326
37,UG,2,2019,financial-inclusion,0.085806,0.001144,59931,#F9C926
102,UG,4,2019,diversification,0.127814,0.001640,41463,#4897CD
118,KE,2,2019,question,0.256829,0.001417,95041,#F9C926
257,UG,2,2019,climate,0.047178,0.000866,59931,#F9C926
124,KE,3,2019,question,0.254783,0.001223,126840,#DC7326
262,UG,3,2019,climate,0.048580,0.000679,100324,#DC7326
267,UG,4,2019,climate,0.047092,0.001040,41463,#4897CD
112,KE,1,2019,question,0.254445,0.001414,94916,#A1A1A1
107,UG,5,2019,diversification,0.128788,0.002141,24485,#2E9999
317,UG,3,2019,disease,0.184409,0.001224,100324,#DC7326
97,UG,3,2019,diversification,0.128325,0.001056,100324,#DC7326
312,UG,2,2019,disease,0.183286,0.001580,59931,#F9C926
344,KE,3,2019,livestock,0.114765,0.000895,126840,#DC7326
185,KE,4,2019,crop,0.191335,0.001583,61710,#4897CD
179,KE,3,2019,crop,0.190008,0.001102,126840,#DC7326
197,UG,1,2019,crop,0.201204,0.001446,76817,#A1A1A1
191,KE,5,2019,crop,0.192564,0.001703,53620,#2E9999
234,KE,3,2019,climate,0.058778,0.000660,126840,#DC7326
240,KE,4,2019,climate,0.057718,0.000939,61710,#4897CD
246,KE,5,2019,climate,0.057185,0.001003,53620,#2E9999
167,KE,1,2019,crop,0.186812,0.001265,94916,#A1A1A1
252,UG,1,2019,climate,0.048977,0.000779,76817,#A1A1A1
162,UG,5,2019,question,0.260579,0.002805,24485,#2E9999
32,UG,1,2019,financial-inclusion,0.083151,0.000996,76817,#A1A1A1
26,KE,5,2019,financial-inclusion,0.073420,0.001126,53620,#2E9999
20,KE,4,2019,financial-inclusion,0.072715,0.001045,61710,#4897CD
14,KE,3,2019,financial-inclusion,0.075705,0.000743,126840,#DC7326
8,KE,2,2019,financial-inclusion,0.076350,0.000861,95041,#F9C926
2,KE,1,2019,financial-inclusion,0.080275,0.000882,94916,#A1A1A1
217,UG,5,2019,crop,0.203016,0.002571,24485,#2E9999
222,KE,1,2019,climate,0.058639,0.000763,94916,#A1A1A1
207,UG,3,2019,crop,0.204669,0.001274,100324,#DC7326
212,UG,4,2019,crop,0.204605,0.001981,41463,#4897CD
202,UG,2,2019,crop,0.199747,0.001633,59931,#F9C926
173,KE,2,2019,crop,0.189728,0.001272,95041,#F9C926
362,UG,1,2019,livestock,0.094286,0.001054,76817,#A1A1A1
367,UG,2,2019,livestock,0.096325,0.001205,59931,#F9C926
372,UG,3,2019,livestock,0.090357,0.000905,100324,#DC7326
356,KE,5,2019,livestock,0.111767,0.001361,53620,#2E9999
377,UG,4,2019,livestock,0.092667,0.001424,41463,#4897CD
382,UG,5,2019,livestock,0.092276,0.001850,24485,#2E9999
378,UG,4,2020,livestock,0.087429,0.001233,52501,#4897CD
383,UG,5,2020,livestock,0.086523,0.001610,30505,#2E9999
363,UG,1,2020,livestock,0.091656,0.000960,90304,#A1A1A1
373,UG,3,2020,livestock,0.088349,0.000786,130244,#DC7326
357,KE,5,2020,livestock,0.111823,0.001765,31899,#2E9999
27,KE,5,2020,financial-inclusion,0.078840,0.001509,31899,#2E9999
368,UG,2,2020,livestock,0.096590,0.001097,72538,#F9C926
21,KE,4,2020,financial-inclusion,0.077197,0.001262,44706,#4897CD
15,KE,3,2020,financial-inclusion,0.079367,0.000859,98982,#DC7326
3,KE,1,2020,financial-inclusion,0.085026,0.001039,72022,#A1A1A1
223,KE,1,2020,climate,0.058644,0.000875,72022,#A1A1A1
218,UG,5,2020,crop,0.200751,0.002293,30505,#2E9999
9,KE,2,2020,financial-inclusion,0.080923,0.001068,65265,#F9C926
208,UG,3,2020,crop,0.200813,0.001110,130244,#DC7326
203,UG,2,2020,crop,0.195649,0.001473,72538,#F9C926
213,UG,4,2020,crop,0.201938,0.001752,52501,#4897CD
163,UG,5,2020,question,0.262116,0.002518,30505,#2E9999
186,KE,4,2020,crop,0.192696,0.001865,44706,#4897CD
192,KE,5,2020,crop,0.194741,0.002217,31899,#2E9999
180,KE,3,2020,crop,0.191427,0.001250,98982,#DC7326
241,KE,4,2020,climate,0.057380,0.001100,44706,#4897CD
174,KE,2,2020,crop,0.190572,0.001537,65265,#F9C926
253,UG,1,2020,climate,0.049679,0.000723,90304,#A1A1A1
168,KE,1,2020,crop,0.186992,0.001453,72022,#A1A1A1
198,UG,1,2020,crop,0.196230,0.001322,90304,#A1A1A1
158,UG,4,2020,question,0.263185,0.001922,52501,#4897CD
137,KE,5,2020,question,0.245009,0.002408,31899,#2E9999
148,UG,2,2020,question,0.265103,0.001639,72538,#F9C926
153,UG,3,2020,question,0.265102,0.001223,130244,#DC7326
229,KE,2,2020,climate,0.060080,0.000930,65265,#F9C926
235,KE,3,2020,climate,0.057891,0.000742,98982,#DC7326
247,KE,5,2020,climate,0.056274,0.001290,31899,#2E9999
258,UG,2,2020,climate,0.048556,0.000798,72538,#F9C926
263,UG,3,2020,climate,0.048127,0.000593,130244,#DC7326
125,KE,3,2020,question,0.247925,0.001373,98982,#DC7326
131,KE,4,2020,question,0.248018,0.002043,44706,#4897CD
278,KE,1,2020,disease,0.172291,0.001407,72022,#A1A1A1
268,UG,4,2020,climate,0.048122,0.000934,52501,#4897CD
119,KE,2,2020,question,0.248542,0.001692,65265,#F9C926
113,KE,1,2020,question,0.247185,0.001607,72022,#A1A1A1
313,UG,2,2020,disease,0.180420,0.001428,72538,#F9C926
308,UG,1,2020,disease,0.179077,0.001276,90304,#A1A1A1
290,KE,3,2020,disease,0.175154,0.001208,98982,#DC7326
302,KE,5,2020,disease,0.175545,0.002130,31899,#2E9999
318,UG,3,2020,disease,0.180307,0.001065,130244,#DC7326
108,UG,5,2020,diversification,0.131615,0.001936,30505,#2E9999
103,UG,4,2020,diversification,0.130566,0.001470,52501,#4897CD
98,UG,3,2020,diversification,0.129594,0.000931,130244,#DC7326
143,UG,1,2020,question,0.263214,0.001465,90304,#A1A1A1
273,UG,5,2020,climate,0.048598,0.001231,30505,#2E9999
284,KE,2,2020,disease,0.172585,0.001479,65265,#F9C926
64,KE,2,2020,diversification,0.130841,0.001320,65265,#F9C926
38,UG,2,2020,financial-inclusion,0.088604,0.001055,72538,#F9C926
323,UG,4,2020,disease,0.180913,0.001680,52501,#4897CD
339,KE,2,2020,livestock,0.116457,0.001256,65265,#F9C926
333,KE,1,2020,livestock,0.117615,0.001200,72022,#A1A1A1
345,KE,3,2020,livestock,0.115161,0.001015,98982,#DC7326
351,KE,4,2020,livestock,0.113654,0.001501,44706,#4897CD
70,KE,3,2020,diversification,0.133076,0.001080,98982,#DC7326
76,KE,4,2020,diversification,0.134314,0.001613,44706,#4897CD
88,UG,1,2020,diversification,0.128629,0.001114,90304,#A1A1A1
82,KE,5,2020,diversification,0.137767,0.001930,31899,#2E9999
93,UG,2,2020,diversification,0.125078,0.001228,72538,#F9C926
296,KE,4,2020,disease,0.176740,0.001804,44706,#4897CD
328,UG,5,2020,disease,0.180914,0.002204,30505,#2E9999
58,KE,1,2020,diversification,0.132247,0.001262,72022,#A1A1A1
53,UG,5,2020,financial-inclusion,0.089482,0.001634,30505,#2E9999
43,UG,3,2020,financial-inclusion,0.087709,0.000784,130244,#DC7326
48,UG,4,2020,financial-inclusion,0.087847,0.001235,52501,#4897CD
33,UG,1,2020,financial-inclusion,0.091514,0.000960,90304,#A1A1A1
114,KE,1,2021,question,0.254240,0.002518,29906,#A1A1A1
109,UG,5,2021,diversification,0.127386,0.002746,14738,#2E9999
138,KE,5,2021,question,0.249329,0.004419,9584,#2E9999
132,KE,4,2021,question,0.251407,0.003875,12535,#4897CD
230,KE,2,2021,climate,0.058099,0.001613,21028,#F9C926
236,KE,3,2021,climate,0.055683,0.001333,29596,#DC7326
149,UG,2,2021,question,0.282142,0.002507,32231,#F9C926
264,UG,3,2021,climate,0.046567,0.000789,71276,#DC7326
126,KE,3,2021,question,0.249028,0.002514,29596,#DC7326
285,KE,2,2021,disease,0.163543,0.002551,21028,#F9C926
319,UG,3,2021,disease,0.166394,0.001395,71276,#DC7326
314,UG,2,2021,disease,0.166659,0.002076,32231,#F9C926
99,UG,3,2021,diversification,0.124692,0.001237,71276,#DC7326
193,KE,5,2021,crop,0.194830,0.004046,9584,#2E9999
364,UG,1,2021,livestock,0.094352,0.001465,39789,#A1A1A1
379,UG,4,2021,livestock,0.091236,0.001824,24931,#4897CD
10,KE,2,2021,financial-inclusion,0.093296,0.002006,21028,#F9C926
22,KE,4,2021,financial-inclusion,0.089109,0.002545,12535,#4897CD
219,UG,5,2021,crop,0.195950,0.003270,14738,#2E9999
181,KE,3,2021,crop,0.187581,0.002269,29596,#DC7326
144,UG,1,2021,question,0.284325,0.002261,39789,#A1A1A1
274,UG,5,2021,climate,0.047175,0.001746,14738,#2E9999
279,KE,1,2021,disease,0.166061,0.002152,29906,#A1A1A1
154,UG,3,2021,question,0.288004,0.001696,71276,#DC7326
159,UG,4,2021,question,0.283380,0.002854,24931,#4897CD
248,KE,5,2021,climate,0.051466,0.002257,9584,#2E9999
303,KE,5,2021,disease,0.169473,0.003832,9584,#2E9999
297,KE,4,2021,disease,0.168801,0.003346,12535,#4897CD
309,UG,1,2021,disease,0.163241,0.001853,39789,#A1A1A1
104,UG,4,2021,diversification,0.125014,0.002095,24931,#4897CD
259,UG,2,2021,climate,0.046769,0.001176,32231,#F9C926
269,UG,4,2021,climate,0.046220,0.001330,24931,#4897CD
334,KE,1,2021,livestock,0.117919,0.001865,29906,#A1A1A1
324,UG,4,2021,disease,0.168964,0.002373,24931,#4897CD
71,KE,3,2021,diversification,0.137802,0.002004,29596,#DC7326
352,KE,4,2021,livestock,0.106958,0.002760,12535,#4897CD
346,KE,3,2021,livestock,0.110251,0.001821,29596,#DC7326
77,KE,4,2021,diversification,0.141826,0.003116,12535,#4897CD
340,KE,2,2021,livestock,0.109909,0.002157,21028,#F9C926
120,KE,2,2021,question,0.253567,0.003000,21028,#F9C926
169,KE,1,2021,crop,0.183885,0.002240,29906,#A1A1A1
164,UG,5,2021,question,0.279796,0.003698,14738,#2E9999
224,KE,1,2021,climate,0.060581,0.001379,29906,#A1A1A1
209,UG,3,2021,crop,0.190403,0.001471,71276,#DC7326
204,UG,2,2021,crop,0.185173,0.002164,32231,#F9C926
254,UG,1,2021,climate,0.048807,0.001080,39789,#A1A1A1
214,UG,4,2021,crop,0.192858,0.002499,24931,#4897CD
175,KE,2,2021,crop,0.185626,0.002681,21028,#F9C926
199,UG,1,2021,crop,0.185396,0.001948,39789,#A1A1A1
187,KE,4,2021,crop,0.189004,0.003497,12535,#4897CD
242,KE,4,2021,climate,0.052896,0.001999,12535,#4897CD
16,KE,3,2021,financial-inclusion,0.089532,0.001660,29596,#DC7326
358,KE,5,2021,livestock,0.104289,0.003122,9584,#2E9999
28,KE,5,2021,financial-inclusion,0.086960,0.002878,9584,#2E9999
4,KE,1,2021,financial-inclusion,0.084775,0.001611,29906,#A1A1A1
369,UG,2,2021,livestock,0.095955,0.001641,32231,#F9C926
374,UG,3,2021,livestock,0.090842,0.001076,71276,#DC7326
384,UG,5,2021,livestock,0.089024,0.002346,14738,#2E9999
44,UG,3,2021,financial-inclusion,0.093098,0.001088,71276,#DC7326
54,UG,5,2021,financial-inclusion,0.092216,0.002383,14738,#2E9999
59,KE,1,2021,diversification,0.132538,0.001961,29906,#A1A1A1
49,UG,4,2021,financial-inclusion,0.092328,0.001833,24931,#4897CD
39,UG,2,2021,financial-inclusion,0.097778,0.001654,32231,#F9C926
34,UG,1,2021,financial-inclusion,0.102253,0.001519,39789,#A1A1A1
94,UG,2,2021,diversification,0.125525,0.001845,32231,#F9C926
291,KE,3,2021,disease,0.170123,0.002184,29596,#DC7326
65,KE,2,2021,diversification,0.135961,0.002364,21028,#F9C926
83,KE,5,2021,diversification,0.143653,0.003583,9584,#2E9999
329,UG,5,2021,disease,0.168453,0.003083,14738,#2E9999
89,UG,1,2021,diversification,0.121626,0.001639,39789,#A1A1A1
133,KE,4,2022,question,0.246330,0.032759,173,#4897CD
231,KE,2,2022,climate,0.061935,0.008253,853,#F9C926

In [44]:
gb_country_segment_n_topic_time_dct = defaultdict(dict)
for segmentation in segmentation_collst:
  for time in time_collst:
    gb_sum = all3.groupby([
      "question_user_country_code",
      segmentation,
      time
    ])[niche_collst].sum()

    gb_count = all3.groupby([
      "question_user_country_code",
      segmentation,
      time
    ]).size()

    row_sums = gb_sum[niche_collst].sum(axis=1)
    gb_pct = gb_sum[niche_collst].div(row_sums, axis=0)
    gb_se = np.sqrt(gb_pct * (1 - gb_pct)).div(np.sqrt(gb_count), axis=0)

    gb_pct = gb_pct.reset_index()
    gb_se = gb_se.reset_index()
    gb_sum = gb_sum.reset_index()
    gb_sum['count'] = gb_count.values

    gb_pct_long = gb_pct.melt(
      id_vars=["question_user_country_code", segmentation, time],
      value_vars=niche_collst,
      var_name="category",
      value_name="pct"
    )

    gb_se_long = gb_se.melt(
      id_vars=["question_user_country_code", segmentation, time],
      value_vars=niche_collst,
      var_name="category",
      value_name="se"
    )

    gb_long = gb_pct_long.merge(
      gb_se_long,
      on=["question_user_country_code", segmentation, time, "category"]
    ).merge(
      gb_sum[["question_user_country_code", segmentation, time, "count"]],
      on=["question_user_country_code", segmentation, time]
    ).sort_values(
      by=time,
      ascending=True
    )

    gb_long["broad_type"] = gb_long["category"].str.split("_").str[0]
    gb_long["niche"] = gb_long["category"].str.split("_").str[1]

    gb_long["segment_color"] = gb_long[segmentation].map(segment_colors_dct)

    gb_country_segment_n_topic_time_dct[segmentation][time] = gb_long

In [45]:
gb_country_segment_n_topic_time_dct["speed_post_response"]["question_set_dt_year"]

,question_user_country_code,speed_post_response,question_set_dt_year,category,pct,se,count,broad_type,niche,segment_color
6485,UG,5,2017,diversification_shift,0.000000,0.000000,625,diversification,shift,#2E9999
6490,KE,1,2017,financial-inclusion_economy,0.000027,0.000094,3046,financial-inclusion,economy,#A1A1A1
6496,KE,2,2017,financial-inclusion_economy,0.000205,0.000262,2992,financial-inclusion,economy,#F9C926
3575,KE,1,2017,crop_land,0.007453,0.001558,3046,crop,land,#A1A1A1
3581,KE,2,2017,crop_land,0.007733,0.001601,2992,crop,land,#F9C926
3587,KE,3,2017,crop_land,0.008042,0.001380,4187,crop,land,#DC7326
12,KE,3,2017,financial-inclusion_price,0.005752,0.001169,4187,financial-inclusion,price,#DC7326
18,KE,4,2017,financial-inclusion_price,0.006850,0.002208,1395,financial-inclusion,price,#4897CD
5490,UG,4,2017,diversification_clear,0.001508,0.001359,815,diversification,clear,#4897CD
45,UG,4,2017,financial-inclusion_price,0.007138,0.002949,815,financial-inclusion,price,#4897CD
50,UG,5,2017,financial-inclusion_price,0.008071,0.003579,625,financial-inclusion,price,#2E9999
55,KE,1,2017,financial-inclusion_sell,0.015257,0.002221,3046,financial-inclusion,sell,#A1A1A1
61,KE,2,2017,financial-inclusion_sell,0.013931,0.002143,2992,financial-inclusion,sell,#F9C926
67,KE,3,2017,financial-inclusion_sell,0.012695,0.001730,4187,financial-inclusion,sell,#DC7326
6475,UG,3,2017,diversification_shift,0.000000,0.000000,2176,diversification,shift,#DC7326
6480,UG,4,2017,diversification_shift,0.000302,0.000608,815,diversification,shift,#4897CD
5540,UG,3,2017,disease_black,0.001376,0.000795,2176,disease,black,#DC7326
1228,KE,4,2017,livestock_chicken,0.018322,0.003591,1395,livestock,chicken,#4897CD
1234,KE,5,2017,livestock_chicken,0.022351,0.003757,1548,livestock,chicken,#2E9999
1240,UG,1,2017,livestock_chicken,0.011540,0.002068,2668,livestock,chicken,#A1A1A1
1245,UG,2,2017,livestock_chicken,0.013565,0.002533,2085,livestock,chicken,#F9C926
1250,UG,3,2017,livestock_chicken,0.013207,0.002447,2176,livestock,chicken,#DC7326
1255,UG,4,2017,livestock_chicken,0.012064,0.003824,815,livestock,chicken,#4897CD
5485,UG,3,2017,diversification_clear,0.001297,0.000772,2176,diversification,clear,#DC7326
1260,UG,5,2017,livestock_chicken,0.009487,0.003878,625,livestock,chicken,#2E9999
1265,KE,1,2017,livestock_poultry,0.020369,0.002559,3046,livestock,poultry,#A1A1A1
1271,KE,2,2017,livestock_poultry,0.018412,0.002458,2992,livestock,poultry,#F9C926
1277,KE,3,2017,livestock_poultry,0.019931,0.002160,4187,livestock,poultry,#DC7326
1283,KE,4,2017,livestock_poultry,0.020334,0.003779,1395,livestock,poultry,#4897CD
5451,KE,2,2017,diversification_clear,0.001511,0.000710,2992,diversification,clear,#F9C926
5457,KE,3,2017,diversification_clear,0.001172,0.000529,4187,diversification,clear,#DC7326
5535,UG,2,2017,disease_black,0.001775,0.000922,2085,disease,black,#F9C926
3560,UG,3,2017,crop_leave,0.005110,0.001528,2176,crop,leave,#DC7326
3565,UG,4,2017,crop_leave,0.003921,0.002189,815,crop,leave,#4897CD
3570,UG,5,2017,crop_leave,0.004106,0.002558,625,crop,leave,#2E9999
3495,UG,1,2017,livestock_milk,0.003247,0.001101,2668,livestock,milk,#A1A1A1
3500,UG,2,2017,livestock_milk,0.003508,0.001295,2085,livestock,milk,#F9C926
3505,UG,3,2017,livestock_milk,0.004324,0.001407,2176,livestock,milk,#DC7326
3510,UG,4,2017,livestock_milk,0.004323,0.002298,815,livestock,milk,#4897CD
3515,UG,5,2017,livestock_milk,0.003257,0.002279,625,livestock,milk,#2E9999
6453,KE,4,2017,diversification_shift,0.000054,0.000197,1395,diversification,shift,#4897CD
3615,UG,3,2017,crop_land,0.011634,0.002299,2176,crop,land,#DC7326
3620,UG,4,2017,crop_land,0.010154,0.003512,815,crop,land,#4897CD
3532,KE,3,2017,crop_leave,0.003023,0.000848,4187,crop,leave,#DC7326
3538,KE,4,2017,crop_leave,0.003045,0.001475,1395,crop,leave,#4897CD
3544,KE,5,2017,crop_leave,0.002489,0.001266,1548,crop,leave,#2E9999
3550,UG,1,2017,crop_leave,0.004918,0.001354,2668,crop,leave,#A1A1A1
3555,UG,2,2017,crop_leave,0.005198,0.001575,2085,crop,leave,#F9C926
73,KE,4,2017,financial-inclusion_sell,0.014734,0.003226,1395,financial-inclusion,sell,#4897CD
79,KE,5,2017,financial-inclusion_sell,0.015763,0.003166,1548,financial-inclusion,sell,#2E9999
85,UG,1,2017,financial-inclusion_sell,0.009707,0.001898,2668,financial-inclusion,sell,#A1A1A1
90,UG,2,2017,financial-inclusion_sell,0.007818,0.001929,2085,financial-inclusion,sell,#F9C926
95,UG,3,2017,financial-inclusion_sell,0.009630,0.002094,2176,financial-inclusion,sell,#DC7326
100,UG,4,2017,financial-inclusion_sell,0.009350,0.003371,815,financial-inclusion,sell,#4897CD
6441,KE,2,2017,diversification_shift,0.000026,0.000093,2992,diversification,shift,#F9C926
6447,KE,3,2017,diversification_shift,0.000037,0.000094,4187,diversification,shift,#DC7326
24,KE,5,2017,financial-inclusion_price,0.007808,0.002237,1548,financial-inclusion,price,#2E9999
6535,UG,4,2017,financial-inclusion_economy,0.000000,0.000000,815,financial-inclusion,economy,#4897CD
6530,UG,3,2017,financial-inclusion_economy,0.000079,0.000190,2176,financial-inclusion,economy,#DC7326
6525,UG,2,2017,financial-inclusion_economy,0.000127,0.000247,2085,financial-inclusion,economy,#F9C926
6520,UG,1,2017,financial-inclusion_economy,0.000129,0.000220,2668,financial-inclusion,economy,#A1A1A1
6540,UG,5,2017,financial-inclusion_economy,0.000283,0.000673,625,financial-inclusion,economy,#2E9999
6,KE,2,2017,financial-inclusion_price,0.007375,0.001564,2992,financial-inclusion,price,#F9C926
6502,KE,3,2017,financial-inclusion_economy,0.000037,0.000094,4187,financial-inclusion,economy,#DC7326
155,UG,4,2017,financial-inclusion_buy,0.010355,0.003546,815,financial-inclusion,buy,#4897CD
160,UG,5,2017,financial-inclusion_buy,0.011611,0.004285,625,financial-inclusion,buy,#2E9999
165,KE,1,2017,diversification_obtain,0.009606,0.001767,3046,diversification,obtain,#A1A1A1
3735,UG,5,2017,livestock_egg,0.003540,0.002376,625,livestock,egg,#2E9999
3740,KE,1,2017,livestock_breed,0.004171,0.001168,3046,livestock,breed,#A1A1A1
3746,KE,2,2017,livestock_breed,0.005070,0.001298,2992,livestock,breed,#F9C926
3752,KE,3,2017,livestock_breed,0.004030,0.000979,4187,livestock,breed,#DC7326
3373,KE,4,2017,disease_chemical,0.003045,0.001475,1395,disease,chemical,#4897CD
3665,UG,2,2017,disease_leave,0.005198,0.001575,2085,disease,leave,#F9C926
6420,UG,3,2017,climate_water,0.000039,0.000134,2176,climate,water,#DC7326
6425,UG,4,2017,climate_water,0.000101,0.000351,815,climate,water,#4897CD
6430,UG,5,2017,climate_water,0.000000,0.000000,625,climate,water,#2E9999
6435,KE,1,2017,diversification_shift,0.000350,0.000339,3046,diversification,shift,#A1A1A1
140,UG,1,2017,financial-inclusion_buy,0.012922,0.002186,2668,financial-inclusion,buy,#A1A1A1
145,UG,2,2017,financial-inclusion_buy,0.009847,0.002162,2085,financial-inclusion,buy,#F9C926
150,UG,3,2017,financial-inclusion_buy,0.011792,0.002314,2176,financial-inclusion,buy,#DC7326
3715,UG,1,2017,livestock_egg,0.003150,0.001085,2668,livestock,egg,#A1A1A1
3720,UG,2,2017,livestock_egg,0.004775,0.001510,2085,livestock,egg,#F9C926
3405,UG,5,2017,disease_chemical,0.003823,0.002469,625,disease,chemical,#2E9999
3410,KE,1,2017,crop_fruit,0.002153,0.000840,3046,crop,fruit,#A1A1A1
3416,KE,2,2017,crop_fruit,0.002663,0.000942,2992,crop,fruit,#F9C926
3422,KE,3,2017,crop_fruit,0.002620,0.000790,4187,crop,fruit,#DC7326
3428,KE,4,2017,crop_fruit,0.002175,0.001247,1395,crop,fruit,#4897CD
3660,UG,1,2017,disease_leave,0.004918,0.001354,2668,disease,leave,#A1A1A1
3434,KE,5,2017,crop_fruit,0.002538,0.001279,1548,crop,fruit,#2E9999
3440,UG,1,2017,crop_fruit,0.002700,0.001005,2668,crop,fruit,#A1A1A1
3445,UG,2,2017,crop_fruit,0.003085,0.001215,2085,crop,fruit,#F9C926
3450,UG,3,2017,crop_fruit,0.002516,0.001074,2176,crop,fruit,#DC7326
3455,UG,4,2017,crop_fruit,0.001810,0.001489,815,crop,fruit,#4897CD
3460,UG,5,2017,crop_fruit,0.003965,0.002514,625,crop,fruit,#2E9999
3703,KE,4,2017,livestock_egg,0.009406,0.002584,1395,livestock,egg,#4897CD
3709,KE,5,2017,livestock_egg,0.010151,0.002548,1548,livestock,egg,#2E9999
3361,KE,2,2017,disease_chemical,0.003508,0.001081,2992,disease,chemical,#F9C926
3367,KE,3,2017,disease_chemical,0.003993,0.000975,4187,disease,chemical,#DC7326
3725,UG,3,2017,livestock_egg,0.003891,0.001335,2176,livestock,egg,#DC7326
3730,UG,4,2017,livestock_egg,0.003720,0.002132,815,livestock,egg,#4897CD
3300,KE,1,2017,disease_prevent,0.004171,0.001168,3046,disease,prevent,#A1A1A1
3306,KE,2,2017,disease_prevent,0.005326,0.001331,2992,disease,prevent,#F9C926
3312,KE,3,2017,disease_prevent,0.005257,0.001118,4187,disease,prevent,#DC7326
3318,KE,4,2017,disease_prevent,0.004241,0.001740,1395,disease,prevent,#4897CD
195,UG,1,2017,diversification_obtain,0.007072,0.001622,2668,diversification,obtain,#A1A1A1
200,UG,2,2017,diversification_obtain,0.006001,0.001691,2085,diversification,obtain,#F9C926
3775,UG,2,2017,livestock_breed,0.002493,0.001092,2085,livestock,breed,#F9C926
3780,UG,3,2017,livestock_breed,0.003577,0.001280,2176,livestock,breed,#DC7326
3340,UG,3,2017,disease_prevent,0.008018,0.001912,2176,disease,prevent,#DC7326
3345,UG,4,2017,disease_prevent,0.006535,0.002822,815,disease,prevent,#4897CD
3350,UG,5,2017,disease_prevent,0.007788,0.003516,625,disease,prevent,#2E9999
3355,KE,1,2017,disease_chemical,0.003014,0.000993,3046,disease,chemical,#A1A1A1
6386,KE,2,2017,climate_water,0.000102,0.000185,2992,climate,water,#F9C926
6392,KE,3,2017,climate_water,0.000073,0.000132,4187,climate,water,#DC7326
6398,KE,4,2017,climate_water,0.000217,0.000395,1395,climate,water,#4897CD
6404,KE,5,2017,climate_water,0.000098,0.000251,1548,climate,water,#2E9999
171,KE,2,2017,diversification_obtain,0.010499,0.001863,2992,diversification,obtain,#F9C926
177,KE,3,2017,diversification_obtain,0.009837,0.001525,4187,diversification,obtain,#DC7326
183,KE,4,2017,diversification_obtain,0.011037,0.002797,1395,diversification,obtain,#4897CD
189,KE,5,2017,diversification_obtain,0.012005,0.002768,1548,diversification,obtain,#2E9999
3379,KE,5,2017,disease_chemical,0.002928,0.001373,1548,disease,chemical,#2E9999
3385,UG,1,2017,disease_chemical,0.003922,0.001210,2668,disease,chemical,#A1A1A1
3390,UG,2,2017,disease_chemical,0.005071,0.001556,2085,disease,chemical,#F9C926
3395,UG,3,2017,disease_chemical,0.004756,0.001475,2176,disease,chemical,#DC7326
3400,UG,4,2017,disease_chemical,0.004423,0.002325,815,disease,chemical,#4897CD
3691,KE,2,2017,livestock_egg,0.007964,0.001625,2992,livestock,egg,#F9C926
3697,KE,3,2017,livestock_egg,0.010497,0.001575,4187,livestock,egg,#DC7326
6380,KE,1,2017,climate_water,0.000188,0.000249,3046,climate,water,#A1A1A1
210,UG,4,2017,diversification_obtain,0.006133,0.002735,815,diversification,obtain,#4897CD
215,UG,5,2017,diversification_obtain,0.007363,0.003420,625,diversification,obtain,#2E9999
220,KE,1,2017,diversification_acquire,0.009606,0.001767,3046,diversification,acquire,#A1A1A1
226,KE,2,2017,diversification_acquire,0.009449,0.001769,2992,diversification,acquire,#F9C926
3825,UG,1,2017,crop_manure,0.002250,0.000917,2668,crop,manure,#A1A1A1
3830,UG,2,2017,crop_manure,0.002324,0.001055,2085,crop,manure,#F9C926
3835,UG,3,2017,crop_manure,0.001572,0.000849,2176,crop,manure,#DC7326
3840,UG,4,2017,crop_manure,0.002513,0.001754,815,crop,manure,#4897CD
3295,UG,5,2017,disease_treat,0.008213,0.003610,625,disease,treat,#2E9999
6349,KE,5,2017,diversification_register,0.000634,0.000640,1548,diversification,register,#2E9999
6355,UG,1,2017,diversification_register,0.000546,0.000452,2668,diversification,register,#A1A1A1
6360,UG,2,2017,diversification_register,0.000211,0.000318,2085,diversification,register,#F9C926
6365,UG,3,2017,diversification_register,0.000511,0.000484,2176,diversification,register,#DC7326
6370,UG,4,2017,diversification_register,0.000101,0.000351,815,diversification,register,#4897CD
6375,UG,5,2017,diversification_register,0.001274,0.001427,625,diversification,register,#2E9999
205,UG,3,2017,diversification_obtain,0.007743,0.001879,2176,diversification,obtain,#DC7326
3795,KE,1,2017,crop_manure,0.001830,0.000774,3046,crop,manure,#A1A1A1
3801,KE,2,2017,crop_manure,0.001511,0.000710,2992,crop,manure,#F9C926
3807,KE,3,2017,crop_manure,0.001630,0.000624,4187,crop,manure,#DC7326
3813,KE,4,2017,crop_manure,0.002338,0.001293,1395,crop,manure,#4897CD
3275,UG,1,2017,disease_treat,0.006879,0.001600,2668,disease,treat,#A1A1A1
3280,UG,2,2017,disease_treat,0.010311,0.002212,2085,disease,treat,#F9C926
3285,UG,3,2017,disease_treat,0.008569,0.001976,2176,disease,treat,#DC7326
3290,UG,4,2017,disease_treat,0.006233,0.002757,815,disease,treat,#4897CD
3324,KE,5,2017,disease_prevent,0.003660,0.001535,1548,disease,prevent,#2E9999
3330,UG,1,2017,disease_prevent,0.006365,0.001540,2668,disease,prevent,#A1A1A1
3335,UG,2,2017,disease_prevent,0.008875,0.002054,2085,disease,prevent,#F9C926
3758,KE,4,2017,livestock_breed,0.005056,0.001899,1395,livestock,breed,#4897CD
3764,KE,5,2017,livestock_breed,0.004539,0.001708,1548,livestock,breed,#2E9999
3770,UG,1,2017,livestock_breed,0.003247,0.001101,2668,livestock,breed,#A1A1A1
3785,UG,4,2017,livestock_breed,0.003217,0.001984,815,livestock,breed,#4897CD
3790,UG,5,2017,livestock_breed,0.003540,0.002376,625,livestock,breed,#2E9999
6320,UG,5,2017,diversification_diversify,0.000142,0.000476,625,diversification,diversify,#2E9999
6325,KE,1,2017,diversification_register,0.000350,0.000339,3046,diversification,register,#A1A1A1
6331,KE,2,2017,diversification_register,0.000359,0.000346,2992,diversification,register,#F9C926
3900,UG,5,2017,diversification_increase,0.002266,0.001902,625,diversification,increase,#2E9999
3905,KE,1,2017,climate_season,0.001722,0.000751,3046,climate,season,#A1A1A1
3911,KE,2,2017,climate_season,0.001434,0.000692,2992,climate,season,#F9C926
3180,UG,4,2017,question_many,0.009953,0.003477,815,question,many,#4897CD
3185,UG,5,2017,question_many,0.007505,0.003452,625,question,many,#2E9999
3819,KE,5,2017,crop_manure,0.001659,0.001034,1548,crop,manure,#2E9999
232,KE,3,2017,diversification_acquire,0.009269,0.001481,4187,diversification,acquire,#DC7326
238,KE,4,2017,diversification_acquire,0.010547,0.002735,1395,diversification,acquire,#4897CD
244,KE,5,2017,diversification_acquire,0.010980,0.002649,1548,diversification,acquire,#2E9999
250,UG,1,2017,diversification_acquire,0.006686,0.001578,2668,diversification,acquire,#A1A1A1
255,UG,2,2017,diversification_acquire,0.006804,0.001800,2085,diversification,acquire,#F9C926
260,UG,3,2017,diversification_acquire,0.006721,0.001752,2176,diversification,acquire,#DC7326
6315,UG,4,2017,diversification_diversify,0.000101,0.000351,815,diversification,diversify,#4897CD
3874,KE,5,2017,diversification_increase,0.002294,0.001216,1548,diversification,increase,#2E9999
3880,UG,1,2017,diversification_increase,0.001929,0.000849,2668,diversification,increase,#A1A1A1
3214,KE,5,2017,crop_layer,0.020643,0.003614,1548,crop,layer,#2E9999
3220,UG,1,2017,crop_layer,0.005818,0.001472,2668,crop,layer,#A1A1A1
3225,UG,2,2017,crop_layer,0.008410,0.002000,2085,crop,layer,#F9C926
3230,UG,3,2017,crop_layer,0.008175,0.001930,2176,crop,layer,#DC7326
3235,UG,4,2017,crop_layer,0.007238,0.002969,815,crop,layer,#4897CD
3240,UG,5,2017,crop_layer,0.005947,0.003076,625,crop,layer,#2E9999
3845,UG,5,2017,crop_manure,0.001841,0.001715,625,crop,manure,#2E9999
3245,KE,1,2017,disease_treat,0.004709,0.001240,3046,disease,treat,#A1A1A1
3251,KE,2,2017,disease_treat,0.005557,0.001359,2992,disease,treat,#F9C926
3257,KE,3,2017,disease_treat,0.005679,0.001161,4187,disease,treat,#DC7326
3263,KE,4,2017,disease_treat,0.004893,0.001868,1395,disease,treat,#4897CD
3269,KE,5,2017,disease_treat,0.003953,0.001595,1548,disease,treat,#2E9999
3862,KE,3,2017,diversification_increase,0.002052,0.000699,4187,diversification,increase,#DC7326
3868,KE,4,2017,diversification_increase,0.002120,0.001232,1395,diversification,increase,#4897CD
293,KE,4,2017,question_what,0.049530,0.005809,1395,question,what,#4897CD
6282,KE,3,2017,diversification_diversify,0.000000,0.000000,4187,diversification,diversify,#DC7326
6288,KE,4,2017,diversification_diversify,0.000000,0.000000,1395,diversification,diversify,#4897CD
6294,KE,5,2017,diversification_diversify,0.000049,0.000178,1548,diversification,diversify,#2E9999
3110,UG,1,2017,financial-inclusion_cost,0.013179,0.002208,2668,financial-inclusion,cost,#A1A1A1
3115,UG,2,2017,financial-inclusion_cost,0.010354,0.002217,2085,financial-inclusion,cost,#F9C926
3120,UG,3,2017,financial-inclusion_cost,0.010966,0.002233,2176,financial-inclusion,cost,#DC7326
3125,UG,4,2017,financial-inclusion_cost,0.014979,0.004255,815,financial-inclusion,cost,#4897CD
3895,UG,4,2017,diversification_increase,0.002513,0.001754,815,diversification,increase,#4897CD
6337,KE,3,2017,diversification_register,0.000513,0.000350,4187,diversification,register,#DC7326
6343,KE,4,2017,diversification_register,0.000272,0.000441,1395,diversification,register,#4897CD
265,UG,4,2017,diversification_acquire,0.006334,0.002779,815,diversification,acquire,#4897CD
270,UG,5,2017,diversification_acquire,0.007222,0.003387,625,diversification,acquire,#2E9999
275,KE,1,2017,question_what,0.051582,0.004008,3046,question,what,#A1A1A1
281,KE,2,2017,question_what,0.050677,0.004010,2992,question,what,#F9C926
287,KE,3,2017,question_what,0.050578,0.003387,4187,question,what,#DC7326
3147,KE,3,2017,question_many,0.006760,0.001266,4187,question,many,#DC7326
3153,KE,4,2017,question_many,0.008916,0.002517,1395,question,many,#4897CD
3159,KE,5,2017,question_many,0.005759,0.001923,1548,question,many,#2E9999
3165,UG,1,2017,question_many,0.008197,0.001746,2668,question,many,#A1A1A1
3170,UG,2,2017,question_many,0.008072,0.001960,2085,question,many,#F9C926
3175,UG,3,2017,question_many,0.007232,0.001816,2176,question,many,#DC7326
3885,UG,2,2017,diversification_increase,0.002493,0.001092,2085,diversification,increase,#F9C926
3890,UG,3,2017,diversification_increase,0.001926,0.000940,2176,diversification,increase,#DC7326
3190,KE,1,2017,crop_layer,0.014988,0.002202,3046,crop,layer,#A1A1A1
3196,KE,2,2017,crop_layer,0.014161,0.002160,2992,crop,layer,#F9C926
3202,KE,3,2017,crop_layer,0.016725,0.001982,4187,crop,layer,#DC7326
3208,KE,4,2017,crop_layer,0.017507,0.003511,1395,crop,layer,#4897CD
3850,KE,1,2017,diversification_increase,0.002018,0.000813,3046,diversification,increase,#A1A1A1
3856,KE,2,2017,diversification_increase,0.001408,0.000686,2992,diversification,increase,#F9C926
3935,UG,1,2017,climate_season,0.002025,0.000870,2668,climate,season,#A1A1A1
3940,UG,2,2017,climate_season,0.001606,0.000877,2085,climate,season,#F9C926
320,UG,4,2017,question_what,0.056902,0.008115,815,question,what,#4897CD
325,UG,5,2017,question_what,0.057066,0.009279,625,question,what,#2E9999
6250,UG,2,2017,diversification_acreage,0.000549,0.000513,2085,diversification,acreage,#F9C926
6255,UG,3,2017,diversification_acreage,0.000314,0.000380,2176,diversification,acreage,#DC7326
3990,UG,1,2017,disease_control,0.003857,0.001200,2668,disease,control,#A1A1A1
3995,UG,2,2017,disease_control,0.006339,0.001738,2085,disease,control,#F9C926
4000,UG,3,2017,disease_control,0.005463,0.001580,2176,disease,control,#DC7326
4005,UG,4,2017,disease_control,0.004222,0.002271,815,disease,control,#4897CD
3104,KE,5,2017,financial-inclusion_cost,0.004831,0.001762,1548,financial-inclusion,cost,#2E9999
6300,UG,1,2017,diversification_diversify,0.000064,0.000155,2668,diversification,diversify,#A1A1A1
6305,UG,2,2017,diversification_diversify,0.000042,0.000142,2085,diversification,diversify,#F9C926
6310,UG,3,2017,diversification_diversify,0.000118,0.000233,2176,diversification,diversify,#DC7326
299,KE,5,2017,question_what,0.051193,0.005602,1548,question,what,#2E9999
305,UG,1,2017,question_what,0.054773,0.004405,2668,question,what,#A1A1A1
310,UG,2,2017,question_what,0.057389,0.005094,2085,question,what,#F9C926
315,UG,3,2017,question_what,0.055774,0.004920,2176,question,what,#DC7326
3950,UG,4,2017,climate_season,0.002011,0.001569,815,climate,season,#4897CD
3955,UG,5,2017,climate_season,0.000991,0.001259,625,climate,season,#2E9999

In [36]:
# gb_country_segment_n_topic_time_dct = defaultdict(dict)
# for segmentation in segmentation_collst:
#   for time in time_collst:
#     gb = all3.groupby([
#       "question_user_country_code",
#       segmentation,
#       time
#     ])[niche_collst].sum().reset_index()

#     row_sums = gb[niche_collst].sum(axis=1)
#     gb[niche_collst] = gb[niche_collst].div(row_sums, axis=0)

#     gb_long = gb.melt(
#       id_vars=["question_user_country_code", segmentation, time],
#       value_vars=gb.columns[2:],
#       var_name="category",
#       value_name="pct"
#     )

#     gb_long["broad_type"] = gb_long["category"].str.split("_").str[0]
#     gb_long["niche"] = gb_long["category"].str.split("_").str[1]

#     gb_long["segment_color"] = gb_long[segmentation].map(segment_colors_dct)

#     gb_country_segment_n_topic_time_dct[segmentation][time] = gb_long

# export data to google drive

In [37]:
alldata_dct = {
  "tab1": vc_country.to_dict(),
  "tab2": gb_segments_dct,
  "tab3": {
    "broad": gb_country_segment_b_topic_dct,
    "niche": gb_country_segment_n_topic_dct
  },
  "tab4": {
    "broad": gb_country_segment_b_topic_time_dct,
    "niche": gb_country_segment_n_topic_time_dct
  }
}

In [38]:
import pickle

with open("all_dashboard_data.pkl", "wb") as w:
  pickle.dump(alldata_dct, w)
!cp all_dashboard_data.pkl /content/drive/MyDrive/DataKit_WeFarm/Dashboard

In [39]:
!ls /content/drive/MyDrive/DataKit_WeFarm/Dashboard

all_dashboard_data.pkl	intersections