In [14]:
#import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import nltk
from nltk.stem import SnowballStemmer
from collections import Counter
import regex

In [15]:
#ensure tokenizer is available
nltk.download('punkt')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\cmetzing\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt.zip.

True

In [2]:
#increase print limits 
pd.set_option('display.max_rows', None)

In [28]:
#read data
df = pd.read_csv(r'C:/Users/cmetzing/Downloads/b0cd514b-b9cc-4972-a0c2-c91726e6d825.csv')

In [29]:
#check out data
df.head(1)

,question_id,question_user_id,question_language,question_content,question_topic,question_sent,response_id,response_user_id,response_language,response_content,...,question_user_country_code,question_user_gender,question_user_dob,question_user_created_at,response_user_type,response_user_status,response_user_country_code,response_user_gender,response_user_dob,response_user_created_at
0,3849056,519124,nyn,E ABA WEFARM OFFICES ZABO NIZISHANGWA NKAHI?,NaN,2017-11-22 12:25:03+00,20691011,200868,nyn,E!23 Omubazi Ni Dudu Cipa',...,ug,NaN,NaN,2017-11-18 13:09:11+00,farmer,live,ug,NaN,NaN,2017-05-09 09:19:33+00

In [30]:
df.dtypes

question_id                    int64
question_user_id               int64
question_language             object
question_content              object
question_topic                object
question_sent                 object
response_id                    int64
response_user_id               int64
response_language             object
response_content              object
response_topic                object
response_sent                 object
question_user_type            object
question_user_status          object
question_user_country_code    object
question_user_gender          object
question_user_dob             object
question_user_created_at      object
response_user_type            object
response_user_status          object
response_user_country_code    object
response_user_gender          object
response_user_dob             object
response_user_created_at      object
dtype: object

In [31]:
#possible language values 
df['question_language'].value_counts()

question_language
eng    11976781
swa     6480848
nyn     1157228
lug      689986
Name: count, dtype: int64

In [32]:
#extract eng data
dfe = df[df['question_language'] == 'eng']

In [33]:
#confirm extraction 
dfe['question_language'].value_counts()

question_language
eng    11976781
Name: count, dtype: int64

In [34]:
#check out Eng data
dfe.head(1)

,question_id,question_user_id,question_language,question_content,question_topic,question_sent,response_id,response_user_id,response_language,response_content,...,question_user_country_code,question_user_gender,question_user_dob,question_user_created_at,response_user_type,response_user_status,response_user_country_code,response_user_gender,response_user_dob,response_user_created_at
1,3849061,521327,eng,Q this goes to wefarm. is it possible to get f...,NaN,2017-11-22 12:25:05+00,4334249,526113,eng,Q1 which stage is marleks last vaccinated,...,ug,NaN,NaN,2017-11-20 11:55:48+00,farmer,zombie,ug,NaN,NaN,2017-11-22 10:13:03+00

In [36]:
#reduce dataset to extract question since single question may have multiple responses 
dfe = dfe[["question_id", "question_user_id","question_content","question_topic","question_sent","question_user_country_code"]]

In [37]:
#keep only one row per unique question
dfe = dfe.drop_duplicates(subset="question_id", keep="first")

In [46]:
#inspect
dfe.head()

,question_id,question_user_id,question_content,question_topic,question_sent,question_user_country_code
1,3849061,521327,Q this goes to wefarm. is it possible to get f...,NaN,2017-11-22 12:25:05+00,ug
9,3849084,6642,Q-i have stock rabbit's urine for 5 weeks mash...,rabbit,2017-11-22 12:25:10+00,ke
15,3849098,526375,Q J Have Mi 10000 Can J Start Aproject Of Pout...,poultry,2017-11-22 12:25:12+00,ug
16,3849100,237506,WHERE DO I GET SEEDS OF COCONUT?,pig,2017-11-22 12:25:12+00,ke
23,3849129,54426,Q#.Which plant has omega3?,plant,2017-11-22 12:25:16+00,ke

In [56]:
dfe.describe(include="all")

,question_id,question_user_id,question_content,question_topic,question_sent,question_user_country_code
count,2.940542e+06,2.940542e+06,2940542,2218544,2940542,2940542
unique,NaN,NaN,2708132,148,2939086,4
top,NaN,NaN,What is crop rotation?,chicken,2018-02-01 17:55:53+00,ke
freq,NaN,NaN,839,265257,7,1665002
mean,2.931697e+07,1.659636e+06,NaN,NaN,NaN,NaN
std,1.615944e+07,1.009599e+06,NaN,NaN,NaN,NaN
min,3.849061e+06,7.000000e+00,NaN,NaN,NaN,NaN
25%,1.533666e+07,8.940460e+05,NaN,NaN,NaN,NaN
50%,2.762343e+07,1.428648e+06,NaN,NaN,NaN,NaN
75%,4.305158e+07,2.477375e+06,NaN,NaN,NaN,NaN
max,5.926151e+07,3.832740e+06,NaN,NaN,NaN,NaN

In [38]:
#check countries for where question user
dfe['question_user_country_code'].value_counts()

question_user_country_code
ke    1665002
ug    1275419
gb        118
tz          3
Name: count, dtype: int64

In [55]:
#check for nulls
dfe.isnull().sum()  #looks like we are missing question topic a lot

question_id                        0
question_user_id                   0
question_content                   0
question_topic                721998
question_sent                      0
question_user_country_code         0
dtype: int64

In [58]:
#missing
(721998/2940542)*100

24.55322862247844

In [52]:
#check question topics
dfe['question_topic'].value_counts()

question_topic
chicken               265257
cattle                253285
maize                 200532
tomato                136091
plant                 123615
pig                    88258
bean                   81836
crop                   78338
banana                 70591
poultry                65525
potato                 56107
rabbit                 54606
cabbage                52850
animal                 49112
goat                   48781
coffee                 45644
onion                  33328
watermelon             26331
sheep                  23848
kale                   23210
wheat                  21402
bee                    21112
livestock              21106
passion-fruit          19541
cassava                18538
peanut                 17918
tree                   17811
tea                    17310
rice                   17176
fish                   15218
sugar-cane             14485
carrot                 13845
bird                   12240
grass                  11950
millet                 11751
vegetable               9642
dog                     9482
duck                    8421
mango                   7277
orange                  6756
melon                   6741
aubergine               6480
avocado                 6464
plantain                6463
sweet-potato            6354
pumpkin                 6015
capsicum                6007
pea                     5306
mushroom                4545
pineapple               4462
paw-paw                 4327
turkey                  4254
apple                   4241
pigeon                  4169
olive                   4029
cotton                  4028
spinach                 3865
soya                    3122
yam                     3085
sunflower               2923
ginger                  2437
cat                     2260
napier-grass            2259
cocoa                   2250
eucalyptus              2195
camel                   2118
garlic                  2096
tobacco                 1785
beetroot                1741
cowpea                  1647
french-bean             1530
taro                    1387
greens                  1306
macademia               1297
mung-bean               1169
cereal                  1100
butternut-squash        1084
strawberry              1031
pear                    1018
miraa                    951
cucumber                 934
jackfruit                887
chilli                   825
lemon                    781
rapeseed                 762
okra                     732
safflower                719
pyrethrum                690
clover                   689
boma-rhodes              651
chia                     618
coconut                  604
tilapia                  535
guinea-fowl              534
sisal                    496
collard-greens           495
desmodium                469
grape                    461
nightshade               414
bamboo                   400
peach                    387
finger-millet            384
lucern                   297
brachiaria-grass         290
cyprus                   287
corriander               284
flax                     258
barley                   257
oat                      251
ostrich                  240
african-nightshade       224
cashew-nut               217
squash                   217
radish                   203
guava                    199
amaranth                 179
locust                   174
broccoli                 153
cauliflower              119
snow-pea                 118
lettuce                  113
courgette                112
black-nightshade         105
gooseberry               101
sesame                   100
guinea-pig                97
parsley                   87
chard                     84
sudan-grass               79
chickpea                  66
leek                      60
asparagus                 55
pigeon-pea                53
caliandra                 44
celery                    38
castor-bean               31
apricot                   30
snap-pea                  28
acacia                    28
lupin                     24
vetch                     22
blackberry                20
leucaena                  17
setaria                   15
mulberry                  13
rye                       11
purple-vetch               7
cranberry                  3
Name: count, dtype: int64

In [60]:
#basic word stem counting setup
stemmer = SnowballStemmer("english")
counter = Counter()

def process_text(text):
    #lowercase and remove non-alphabetic characters
    tokens = regex.findall(r'\b\w+\b', str(text).lower())
    stems = [stemmer.stem(token) for token in tokens]
    return stems

In [61]:
# Process each row and update stem counts
for row in dfe['question_content']:
    stems = process_text(row)
    counter.update(stems)

In [42]:
counter

Counter({'q': 1549075,
         'is': 964418,
         'i': 962786,
         'what': 938189,
         'to': 896895,
         'the': 884224,
         'of': 880628,
         'how': 699114,
         'can': 685831,
         'in': 672002,
         'which': 473894,
         'a': 462172,
         'my': 364652,
         'do': 362454,
         'and': 354005,
         'for': 353014,
         'plant': 339330,
         'are': 272405,
         'it': 252534,
         'best': 244175,
         'maiz': 240688,
         'use': 226725,
         'be': 186732,
         'cow': 186037,
         'have': 166749,
         'type': 157318,
         'get': 155301,
         'that': 153705,
         'tomato': 152130,
         'on': 147548,
         'farm': 141594,
         'ask': 139700,
         'where': 131389,
         'when': 116454,
         'doe': 115863,
         'one': 114972,
         'mani': 114723,
         'by': 114275,
         'from': 112289,
         'grow': 107712,
         'me': 107331,
         'good': 106483,
         'take': 103538,
         'much': 102927,
         'control': 101283,
         '2': 101200,
         'bean': 100451,
         'should': 97841,
         'give': 97286,
         'crop': 96929,
         'want': 96679,
         'we': 94259,
         'seed': 92082,
         'long': 90400,
         'with': 89526,
         'hen': 85369,
         'caus': 85091,
         'chick': 85058,
         'farmer': 85041,
         'your': 84705,
         'banana': 84413,
         'am': 84020,
         'at': 83849,
         'diseas': 82421,
         'you': 82184,
         'chicken': 81186,
         'whi': 80461,
         'start': 78770,
         's': 77999,
         'repli': 75863,
         'price': 75031,
         'follow': 73938,
         'feed': 70618,
         'pig': 70064,
         'if': 69281,
         'soil': 65854,
         'egg': 65778,
         'respons': 65105,
         'spray': 64980,
         'need': 64807,
         'market': 64037,
         'has': 63976,
         'poultri': 63626,
         'fertil': 63139,
         'milk': 63080,
         'potato': 62374,
         'they': 61399,
         'season': 61365,
         'this': 61313,
         'know': 61281,
         'or': 61084,
         'will': 60524,
         'goat': 58259,
         'but': 57056,
         'wat': 56717,
         'time': 56533,
         'anim': 56235,
         'after': 54240,
         'cabbag': 53935,
         'like': 53540,
         'month': 53526,
         'rabbit': 53090,
         'not': 52270,
         'chemic': 51661,
         'them': 51229,
         '4': 50787,
         'u': 50663,
         'hw': 50529,
         'make': 50165,
         'coffe': 49764,
         'breed': 49485,
         'keep': 49392,
         'day': 48143,
         'medicin': 48072,
         'e': 47802,
         'wefarm': 47750,
         'problem': 47506,
         'harvest': 47481,
         'there': 45087,
         'product': 44972,
         'produc': 44694,
         'help': 43808,
         'some': 43362,
         'prevent': 42561,
         'dri': 42340,
         'who': 41429,
         'fruit': 41426,
         'now': 40735,
         'leav': 40426,
         'varieti': 39435,
         'an': 39355,
         'counti': 39136,
         'cattl': 39032,
         'onion': 38434,
         'dairi': 38421,
         'well': 38178,
         'plantat': 37828,
         'so': 37614,
         'as': 37391,
         'weed': 36984,
         'water': 36815,
         'improv': 35765,
         'ani': 35448,
         'matur': 34979,
         'about': 34719,
         'land': 34633,
         'name': 34051,
         'appli': 34021,
         'stop': 33896,
         'area': 33815,
         'method': 33726,
         'way': 33720,
         'affect': 33423,
         'l': 33222,
         'cost': 33150,
         'food': 32555,
         'rear': 32267,
         'lay': 31948,
         'pest': 31782,
         'garden': 31559,
         'dure': 31471,
         'would': 30697,
         'treat': 30102,
         'eat': 30069,
         'qn': 29181,
         'tree': 28261,
         'more': 27823,
         'young': 27720,
         'space': 27646,
         'per': 27365,
         'kind': 27095,
         'sell': 27009,
         'sheep': 26442,
         'their': 26426,
         'flower': 25769,
         'call': 25725,
         'could': 25686,
         'acr': 25241,
         'buy': 24546,
         '6333': 24377,
         'seedl': 24141,
         'period': 24078,
         'other': 23995,
         'rain': 23953,
         'old': 23542,
         'da': 23410,
         'birth': 23389,
         'bee': 23274,
         'up': 23236,
         'optout': 23059,
         'calf': 22934,
         'suitabl': 22743,
         't': 22585,
         'yellow': 22562,
         'qwhat': 22547,
         'z': 22418,
         'layer': 22074,
         'livestock': 21969,
         'yield': 21908,
         'vaccin': 21787,
         'kienyeji': 21773,
         'two': 21760,
         'import': 21738,
         'sign': 21709,
         'manur': 21553,
         'drug': 21485,
         'high': 21271,
         'no': 20905,
         'passion': 20878,
         'question': 20782,
         'wilt': 20697,
         'tea': 20625,
         'cassava': 20586,
         'readi': 20430,
         'deworm': 20365,
         'mean': 20287,
         'rice': 20231,
         'given': 20131,
         'most': 20118,
         'die': 19839,
         'kill': 19784,
         'befor': 19704,
         'week': 19615,
         'n': 19532,
         'watermelon': 19453,
         'small': 19447,
         'heat': 19421,
         'pleas': 19353,
         'bed': 19099,
         'ov': 19076,
         'did': 19067,
         'attack': 19065,
         '1': 19063,
         'grass': 18851,
         'kg': 18768,
         'de': 18736,
         'uganda': 18703,
         'local': 18597,
         'qualiti': 18321,
         'fish': 17920,
         'stage': 17798,
         'all': 17783,
         'manag': 17671,
         'green': 17633,
         'iz': 17535,
         'thank': 17496,
         'grown': 17318,
         'effect': 17168,
         'bird': 17134,
         'out': 16877,
         'was': 16832,
         'prepar': 16657,
         'find': 16555,
         'irish': 16492,
         'year': 16107,
         'carrot': 15854,
         'money': 15838,
         'hous': 15833,
         'requir': 15743,
         'kenya': 15647,
         'tell': 15542,
         'been': 14930,
         'agricultur': 14907,
         'between': 14900,
         'answer': 14764,
         'sukuma': 14659,
         'bull': 14192,
         'advis': 14134,
         'put': 13977,
         'piglet': 13952,
         'top': 13847,
         'pesticid': 13702,
         'tick': 13667,
         'g': 13451,
         '3': 13428,
         'mix': 13328,
         'eye': 13289,
         'go': 13054,
         'care': 12946,
         'may': 12883,
         'transplant': 12863,
         'look': 12833,
         'worm': 12827,
         'first': 12812,
         'advic': 12808,
         'herbicid': 12797,
         'bag': 12733,
         'afarm': 12728,
         'black': 12720,
         'qhow': 12656,
         'growth': 12552,
         'increas': 12528,
         'district': 12503,
         'differ': 12451,
         'better': 12451,
         'iam': 12407,
         'come': 12279,
         'nurseri': 12158,
         'hatch': 12142,
         'salt': 12112,
         'our': 12111,
         'place': 12071,
         'melon': 12050,
         'veget': 12023,
         'big': 11873,
         'turn': 11821,
         'sugarcan': 11813,
         'cough': 11784,
         'bt': 11707,
         'measur': 11684,
         'sweet': 11616,
         'becom': 11595,
         'number': 11503,
         'apart': 11479,
         'plz': 11428,
         'than': 11402,
         'pregnant': 11391,
         'iwant': 11273,
         'right': 11269,
         'wiki': 11226,
         'procedur': 11193,
         'mouth': 11187,
         'nut': 11166,
         'veri': 11165,
         'then': 10954,
         'treatment': 10950,
         'factor': 10790,
         'qwhich': 10704,
         'germin': 10595,
         'j': 10594,
         'yet': 10585,
         'order': 10477,
         'around': 10408,
         'without': 10407,
         'term': 10382,
         'kale': 10336,
         'dress': 10256,
         'might': 10220,
         'dog': 10133,
         'destroy': 10125,
         'rotat': 10032,
         'bomet': 9965,
         'b': 9935,
         'white': 9862,
         'mango': 9826,
         'reason': 9735,
         'suppos': 9710,
         'found': 9685,
         'rot': 9602,
         'broiler': 9591,
         'sale': 9474,
         'fertilis': 9463,
         'millet': 9455,
         'while': 9440,
         'mulch': 9439,
         'male': 9427,
         'also': 9396,
         'three': 9318,
         'cure': 9292,
         'main': 9289,
         'colour': 9250,
         'wich': 9182,
         'possibl': 9174,
         'same': 9146,
         'mate': 9121,
         'age': 9111,
         'say': 9084,
         'advantag': 9071,
         'even': 9049,
         'sick': 9044,
         'done': 9011,
         'femal': 8977,
         'castrat': 8817,
         'becaus': 8816,
         'work': 8798,
         'foot': 8788,
         'fall': 8780,
         'contact': 8756,
         'peopl': 8732,
         'hole': 8693,
         'condit': 8690,
         'still': 8665,
         'calv': 8613,
         'part': 8590,
         'each': 8478,
         'faster': 8472,
         'onli': 8438,
         'insect': 8400,
         'consid': 8389,
         'blight': 8379,
         'gestat': 8315,
         'chang': 8304,
         'benefit': 8292,
         'cock': 8266,
         'region': 8202,
         'plan': 8199,
         'eros': 8184,
         'ur': 8150,
         'project': 8147,
         'wht': 8116,
         'remov': 8115,
         'those': 8032,
         'western': 8015,
         'd': 7972,
         'groundnut': 7948,
         'r': 7922,
         'were': 7907,
         'meat': 7898,
         'red': 7872,
         'm': 7807,
         'off': 7756,
         'urin': 7751,
         'profit': 7749,
         'down': 7714,
         'got': 7688,
         'current': 7666,
         'avoid': 7637,
         'honey': 7637,
         'duck': 7615,
         'en': 7613,
         'just': 7605,
         'dat': 7590,
         'organ': 7585,
         'show': 7573,
         'cut': 7554,
         'hybrid': 7540,
         'stem': 7521,
         'capit': 7493,
         'member': 7471,
         'sack': 7444,
         'raini': 7436,
         'step': 7423,
         'low': 7391,
         'short': 7371,
         'pestcid': 7367,
         '5': 7309,
         'alot': 7307,
         'these': 7301,
         'bungoma': 7298,
         'exampl': 7275,
         'true': 7268,
         'yellowish': 7260,
         'new': 7257,
         'skin': 7251,
         'his': 7221,
         'don': 7179,
         'live': 7155,
         'here': 7151,
         'kericho': 7146,
         'practic': 7110,
         'anoth': 7089,
         'pea': 7041,
         'size': 7016,
         'orang': 7000,
         'acow': 6944,
         'last': 6937,
         'suffer': 6897,
         'common': 6871,
         'shamba': 6837,
         'kilo': 6797,
         'field': 6795,
         'graze': 6779,
         'fever': 6778,
         'mi': 6762,
         'store': 6747,
         'larg': 6734,
         'dont': 6732,
         'earli': 6725,
         'graft': 6705,
         'irrig': 6656,
         'yes': 6649,
         'ihav': 6618,
         'spot': 6583,
         'he': 6580,
         'blood': 6574,
         'root': 6573,
         'c': 6572,
         'head': 6571,
         'state': 6475,
         'too': 6467,
         'topdress': 6460,
         'protect': 6457,
         'fast': 6457,
         'heifer': 6408,
         'someon': 6392,
         'loan': 6384,
         'wound': 6364,
         'her': 6363,
         '1kg': 6342,
         'within': 6322,
         'bring': 6314,
         'over': 6287,
         'avocado': 6281,
         'solut': 6258,
         'kgs': 6213,
         'reduc': 6202,
         'wil': 6189,
         'kilogram': 6186,
         'coz': 6163,
         'bodi': 6161,
         'havest': 6095,
         'f1': 6088,
         'incub': 6049,
         'soya': 6018,
         'mash': 5998,
         'climat': 5957,
         'serv': 5950,
         'recommend': 5948,
         'stay': 5928,
         'bacteria': 5926,
         'mastiti': 5889,
         'poutri': 5867,
         'hv': 5848,
         'armi': 5847,
         'sugar': 5802,
         'litr': 5797,
         'had': 5771,
         'artifici': 5760,
         'sukumawiki': 5758,
         'end': 5705,
         'shall': 5693,
         'nandi': 5667,
         'taken': 5651,
         'appl': 5639,
         'locat': 5637,
         'today': 5600,
         'nakuru': 5598,
         'normal': 5589,
         'kampala': 5588,
         'urea': 5557,
         'into': 5534,
         'under': 5500,
         'scale': 5491,
         'hive': 5437,
         'kakamega': 5437,
         'frm': 5429,
         'develop': 5421,
         'health': 5413,
         'whch': 5412,
         'join': 5408,
         'she': 5392,
         'healthi': 5350,
         'maintain': 5342,
         'everi': 5326,
         'te': 5322,
         'correct': 5306,
         'cn': 5280,
         'pliz': 5217,
         'ok': 5213,
         'pumpkin': 5179,
         'cous': 5179,
         'process': 5168,
         'wen': 5121,
         'hi': 5101,
         'especi': 5098,
         'enough': 5091,
         'chiken': 5079,
         'dap': 5046,
         'newcastl': 5040,
         'gd': 5033,
         'ido': 5029,
         'system': 5011,
         'cane': 4982,
         'thing': 4951,
         'drop': 4940,
         'town': 4903,
         'leg': 4898,
         'cotton': 4895,
         'amount': 4862,
         'tri': 4861,
         'kept': 4855,
         'cold': 4843,
         'turkey': 4832,
         'such': 4806,
         'zero': 4774,
         'assist': 4764,
         'both': 4754,
         'weak': 4750,
         'us': 4746,
         'exot': 4743,
         'morn': 4730,
         'leaf': 4726,
         'explain': 4725,
         'pawpaw': 4723,
         'spinach': 4664,
         'seedb': 4662,
         'add': 4657,
         'gave': 4650,
         'parasit': 4641,
         'ph': 4636,
         'next': 4632,
         'wheat': 4609,
         '10': 4605,
         'na': 4574,
         'silag': 4573,
         'human': 4562,
         'expect': 4538,
         'busi': 4538,
         'cultiv': 4529,
         'resist': 4512,
         'famer': 4511,
         'offic': 4500,
         'sinc': 4487,
         'again': 4457,
         'insecticid': 4452,
         'see': 4440,
         'fail': 4427,
         'ya': 4424,
         'gud': 4395,
         'npk': 4392,
         'happen': 4383,
         'symptom': 4366,
         'alway': 4343,
         'half': 4341,
         'proper': 4318,
         'dig': 4313,
         'mother': 4308,
         'heavi': 4303,
         'bad': 4295,
         'four': 4295,
         'eggplant': 4289,
         'agood': 4288,
         'meal': 4275,
         '100': 4273,
         'wet': 4265,
         'near': 4235,
         'paper': 4234,
         'cross': 4214,
         'sex': 4212,
         'send': 4199,
         'free': 4195,
         'friend': 4186,
         'side': 4180,
         'cash': 4162,
         'carri': 4147,
         'full': 4140,
         'fli': 4132,
         'quantiti': 4130,
         'face': 4102,
         'drink': 4090,
         'mushroom': 4077,
         'ground': 4072,
         'lack': 4071,
         'mbarara': 4063,
         'btn': 4048,
         'pond': 4028,
         'weather': 4023,
         'narok': 4015,
         'swollen': 4008,
         'rabit': 4006,
         'ma': 4004,
         'ni': 4002,
         'piec': 3994,
         've': 3994,
         'reach': 3989,
         'select': 3985,
         'pepper': 3984,
         'im': 3972,
         'group': 3953,
         'materi': 3940,
         'east': 3925,
         'eaten': 3920,
         'hve': 3902,
         'rat': 3902,
         'remedi': 3886,
         'home': 3853,
         'must': 3853,
         '20': 3851,
         'fellow': 3845,
         'iget': 3844,
         'favour': 3825,
         'anyon': 3819,
         'rainfal': 3816,
         'bear': 3794,
         'yam': 3775,
         'infect': 3754,
         'fed': 3751,
         'wrong': 3735,
         'appropri': 3721,
         'function': 3713,
         'eg': 3701,
         'medic': 3684,
         'weight': 3680,
         'back': 3647,
         'dehorn': 3644,
         'grade': 3644,
         'sub': 3643,
         'coccidiosi': 3642,
         'defin': 3641,
         'intercrop': 3629,
         'direct': 3628,
         'aphid': 3622,
         'coff': 3606,
         'foliar': 3605,
         'purpos': 3595,
         'stock': 3594,
         'spread': 3590,
         'compani': 3577,
         'night': 3576,
         'pineappl': 3576,
         'alreadi': 3570,
         'p': 3550,
         'fowl': 3550,
         'person': 3549,
         'provid': 3548,
         'speci': 3544,
         '4rm': 3532,
         'highland': 3524,
         'sorghum': 3521,
         'hello': 3519,
         'inject': 3508,
         'rais': 3498,
         'y': 3498,
         'ad': 3496,
         'deliv': 3495,
         'hot': 3483,
         'fat': 3471,
         'poor': 3464,
         'w': 3459,
         'vanilla': 3417,
         'abl': 3403,
         'littl': 3402,
         'tel': 3402,
         'late': 3387,
         'through': 3377,
         'deal': 3373,
         'away': 3334,
         'disadvantag': 3328,
         'armyworm': 3324,
         'wt': 3293,
         'five': 3285,
         'deseas': 3284,
         'warm': 3277,
         'wish': 3268,
         'tool': 3261,
         'stand': 3258,
         'almost': 3246,
         'apig': 3226,
         'lead': 3225,
         'prun': 3220,
         'maximum': 3220,
         'swell': 3214,
         'gram': 3196,
         'word': 3189,
         'english': 3180,
         'list': 3173,
         'identifi': 3165,
         'kuku': 3155,
         '50': 3154,
         'ago': 3152,
         'cours': 3147,
         'bacteri': 3142,
         'natur': 3135,
         'wc': 3133,
         'ai': 3131,
         'piggeri': 3130,
         'buyer': 3125,
         'rust': 3124,
         'open': 3119,
         'due': 3117,
         'bright': 3117,
         'rate': 3116,
         'death': 3113,
         'coast': 3109,
         'sunflow': 3108,
         'sold': 3107,
         'insemin': 3099,
         'against': 3093,
         'ovacado': 3093,
         'ripe': 3091,
         'sucker': 3089,
         'rare': 3088,
         'blind': 3081,
         'busia': 3077,
         'john': 3075,
         'daili': 3067,
         'hoho': 3067,
         'b4': 3065,
         'sow': 3047,
         'togeth': 3046,
         'quick': 3042,
         'sleep': 3042,
         'qwhere': 3030,
         'nose': 3025,
         'hav': 3021,
         '6': 3018,
         'construct': 3017,
         'input': 3010,
         'line': 3009,
         'shop': 3006,
         'miner': 2984,
         'propag': 2975,
         'countri': 2967,
         'let': 2967,
         'support': 2963,
         'among': 2961,
         'cabbeg': 2954,
         'fungicid': 2952,
         'eldoret': 2934,
         'napier': 2930,
         'meant': 2929,
         'feather': 2925,
         'characterist': 2924,
         'sh': 2923,
         'boost': 2918,
         'begin': 2912,
         'life': 2910,
         'apli': 2908,
         'nt': 2904,
         'made': 2893,
         'cat': 2893,
         'acid': 2883,
         'kid': 2876,
         'insid': 2871,
         'cal': 2861,
         'machin': 2860,
         'nutrient': 2858,
         'pregnanc': 2857,
         'specif': 2852,
         'sometim': 2845,
         'activ': 2840,
         'recomend': 2838,
         'french': 2837,
         'prune': 2835,
         'lactat': 2811,
         'dose': 2806,
         'gloria': 2794,
         'wait': 2788,
         'preserv': 2781,
         'managu': 2781,

In [62]:
#write counts to csv
counts = pd.DataFrame(counter.items(), columns=['item', 'count'])
counts.to_csv('allstemcounter_output.csv', index=False)

In [89]:
#manual inspect key stems
target_stem = "unprofit"
matching_questions = []

for row in dfe['question_content']:
    stems = process_text(row)
    if target_stem in stems:
        matching_questions.append(row)

# Now matching_questions contains all question_contents with the chosen stem
for q in matching_questions:
    print(q)

Q In usin-Gishu maize farming as become unprofitable which other crops can u advise the farmers of uasin-gishu to grow
q which crop is unprofitable in uganda?
s if kept over that age by many weeks they are likely to be unprofitable.the enterprise must be organised to have the contracted number ready for marketi
Q what makes layers poultry unprofitable to keep
Q what makes layers poultry unprofitable to keep
Q A farmer asks: what makes layers poultry unprofitable to keep?
Jina asks: A farmer asks: what makes layers poultry unprofitable to keep?
Q88:Jina asks: A farmer asks: what makes layers poultry unprofitable to keep?

In [99]:
keywords = ["unprofitable"]
keywords_lower = set(k.lower() for k in keywords)

def contains_keyword(text):
    # Tokenize words only (ignore punctuation)
    tokens = set(regex.findall(r'\b\w+\b', str(text).lower()))
    return bool(tokens & keywords_lower)

dfe['contains_keyword'] = dfe['question_content'].apply(contains_keyword)

In [100]:
dfe.head()

,question_id,question_user_id,question_content,question_topic,question_sent,question_user_country_code,contains_keyword,contains_keyworda
1,3849061,521327,Q this goes to wefarm. is it possible to get f...,NaN,2017-11-22 12:25:05+00,ug,False,False
9,3849084,6642,Q-i have stock rabbit's urine for 5 weeks mash...,rabbit,2017-11-22 12:25:10+00,ke,False,False
15,3849098,526375,Q J Have Mi 10000 Can J Start Aproject Of Pout...,poultry,2017-11-22 12:25:12+00,ug,False,False
16,3849100,237506,WHERE DO I GET SEEDS OF COCONUT?,pig,2017-11-22 12:25:12+00,ke,False,False
23,3849129,54426,Q#.Which plant has omega3?,plant,2017-11-22 12:25:16+00,ke,False,False

In [101]:
subset_dfe = dfe[dfe["contains_keyword"] == True]

In [102]:
subset_dfe

,question_id,question_user_id,question_content,question_topic,question_sent,question_user_country_code,contains_keyword,contains_keyworda
2858040,11144259,1077212,Q In usin-Gishu maize farming as become unprof...,crop,2018-09-15 17:49:18.572874+00,ke,True,True
11824279,34554053,2219636,q which crop is unprofitable in uganda?,crop,2019-11-22 16:04:13.135536+00,ug,True,True
15341368,45857192,33010,s if kept over that age by many weeks they are...,NaN,2020-08-13 16:50:06.549966+00,ke,True,True
20292380,59204195,3510445,Q what makes layers poultry unprofitable to keep,chicken,2022-02-03 13:06:43.99644+00,ke,True,True
20292382,59204197,3768170,Q what makes layers poultry unprofitable to keep,chicken,2022-02-03 13:07:27.234141+00,ke,True,True
20292403,59204403,3745919,Q A farmer asks: what makes layers poultry unp...,chicken,2022-02-03 16:12:46.811369+00,ke,True,True
20292414,59204455,3614926,Jina asks: A farmer asks: what makes layers po...,chicken,2022-02-03 16:39:04.854541+00,ke,True,True
20292446,59204457,3614926,Q88:Jina asks: A farmer asks: what makes layer...,chicken,2022-02-03 16:40:42.618912+00,ke,True,True